// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Operation {
    "type": string;
    "sourcePath"?: string;
    "targetPath": string;
    "backupPath"?: string;
    "sha256"?: string;
    "sizeBytes"?: number;

    /** Creates a new Operation instance. */
    constructor($$source: Partial<Operation> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("targetPath" in $$source)) {
            this["targetPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Operation instance from a string or object.
     */
    static createFrom($$source: any = {}): Operation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Operation($$parsedSource as Partial<Operation>);
    }
}
