// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class StrategyDescriptor {
    "type": StrategyType;
    "label": string;
    "description": string;
    "visibility": StrategyVisibility;
    "requiresTargetPath": boolean;

    /** Creates a new StrategyDescriptor instance. */
    constructor($$source: Partial<StrategyDescriptor> = {}) {
        if (!("type" in $$source)) {
            this["type"] = StrategyType.$zero;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("visibility" in $$source)) {
            this["visibility"] = StrategyVisibility.$zero;
        }
        if (!("requiresTargetPath" in $$source)) {
            this["requiresTargetPath"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StrategyDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): StrategyDescriptor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StrategyDescriptor($$parsedSource as Partial<StrategyDescriptor>);
    }
}

export enum StrategyType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StrategyTypeGenericCopy = "generic_copy",
    StrategyTypeReplaceFiles = "replace_files",
    StrategyTypeBepInEx = "bepinex",
    StrategyTypeUnrealPak = "unreal_pak",
};

export enum StrategyVisibility {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StrategyVisibilitySelectable = "selectable",
    StrategyVisibilityDisabled = "disabled",
    StrategyVisibilityInternal = "internal",
};
