// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Preview {
    "StrategyType": StrategyType;
    "TargetBase": string;
    "TargetRelativePath": string;
    "TargetDisplayPath": string;
    "TotalFileCount": number;
    "TotalDirectoryCount": number;
    "TargetFilePaths": string[];
    "IsCapped": boolean;
    "Cap": number;
    "Warnings": string[];

    /** Creates a new Preview instance. */
    constructor($$source: Partial<Preview> = {}) {
        if (!("StrategyType" in $$source)) {
            this["StrategyType"] = StrategyType.$zero;
        }
        if (!("TargetBase" in $$source)) {
            this["TargetBase"] = "";
        }
        if (!("TargetRelativePath" in $$source)) {
            this["TargetRelativePath"] = "";
        }
        if (!("TargetDisplayPath" in $$source)) {
            this["TargetDisplayPath"] = "";
        }
        if (!("TotalFileCount" in $$source)) {
            this["TotalFileCount"] = 0;
        }
        if (!("TotalDirectoryCount" in $$source)) {
            this["TotalDirectoryCount"] = 0;
        }
        if (!("TargetFilePaths" in $$source)) {
            this["TargetFilePaths"] = [];
        }
        if (!("IsCapped" in $$source)) {
            this["IsCapped"] = false;
        }
        if (!("Cap" in $$source)) {
            this["Cap"] = 0;
        }
        if (!("Warnings" in $$source)) {
            this["Warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preview instance from a string or object.
     */
    static createFrom($$source: any = {}): Preview {
        const $$createField6_0 = $$createType0;
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("TargetFilePaths" in $$parsedSource) {
            $$parsedSource["TargetFilePaths"] = $$createField6_0($$parsedSource["TargetFilePaths"]);
        }
        if ("Warnings" in $$parsedSource) {
            $$parsedSource["Warnings"] = $$createField9_0($$parsedSource["Warnings"]);
        }
        return new Preview($$parsedSource as Partial<Preview>);
    }
}

export class StrategyDescriptor {
    "Type": StrategyType;
    "Label": string;
    "Description": string;
    "Visibility": StrategyVisibility;
    "RequiresTargetPath": boolean;

    /** Creates a new StrategyDescriptor instance. */
    constructor($$source: Partial<StrategyDescriptor> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = StrategyType.$zero;
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("Visibility" in $$source)) {
            this["Visibility"] = StrategyVisibility.$zero;
        }
        if (!("RequiresTargetPath" in $$source)) {
            this["RequiresTargetPath"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StrategyDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): StrategyDescriptor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StrategyDescriptor($$parsedSource as Partial<StrategyDescriptor>);
    }
}

export enum StrategyType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StrategyTypeGenericCopy = "generic_copy",
    StrategyTypeReplaceFiles = "replace_files",
    StrategyTypeBepInEx = "bepinex",
    StrategyTypeUnrealPak = "unreal_pak",
};

export enum StrategyVisibility {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StrategyVisibilitySelectable = "selectable",
    StrategyVisibilityDisabled = "disabled",
    StrategyVisibilityInternal = "internal",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
