// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppliedDirectoryManifestEntry {
    "OperationIndex": number;
    "Mod": ModContext;
    "TargetPath": string;

    /** Creates a new AppliedDirectoryManifestEntry instance. */
    constructor($$source: Partial<AppliedDirectoryManifestEntry> = {}) {
        if (!("OperationIndex" in $$source)) {
            this["OperationIndex"] = 0;
        }
        if (!("Mod" in $$source)) {
            this["Mod"] = (new ModContext());
        }
        if (!("TargetPath" in $$source)) {
            this["TargetPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppliedDirectoryManifestEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): AppliedDirectoryManifestEntry {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mod" in $$parsedSource) {
            $$parsedSource["Mod"] = $$createField1_0($$parsedSource["Mod"]);
        }
        return new AppliedDirectoryManifestEntry($$parsedSource as Partial<AppliedDirectoryManifestEntry>);
    }
}

export class AppliedFileManifestEntry {
    "OperationIndex": number;
    "Mod": ModContext;
    "SourcePath": string;
    "TargetPath": string;
    "SHA256": string;
    "SizeBytes": number;

    /** Creates a new AppliedFileManifestEntry instance. */
    constructor($$source: Partial<AppliedFileManifestEntry> = {}) {
        if (!("OperationIndex" in $$source)) {
            this["OperationIndex"] = 0;
        }
        if (!("Mod" in $$source)) {
            this["Mod"] = (new ModContext());
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }
        if (!("TargetPath" in $$source)) {
            this["TargetPath"] = "";
        }
        if (!("SHA256" in $$source)) {
            this["SHA256"] = "";
        }
        if (!("SizeBytes" in $$source)) {
            this["SizeBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppliedFileManifestEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): AppliedFileManifestEntry {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mod" in $$parsedSource) {
            $$parsedSource["Mod"] = $$createField1_0($$parsedSource["Mod"]);
        }
        return new AppliedFileManifestEntry($$parsedSource as Partial<AppliedFileManifestEntry>);
    }
}

export class AppliedOperationManifest {
    "AddedFiles": AppliedFileManifestEntry[];
    "ReplacedFiles": ReplacedFileManifestEntry[];
    "CreatedDirectories": AppliedDirectoryManifestEntry[];

    /** Creates a new AppliedOperationManifest instance. */
    constructor($$source: Partial<AppliedOperationManifest> = {}) {
        if (!("AddedFiles" in $$source)) {
            this["AddedFiles"] = [];
        }
        if (!("ReplacedFiles" in $$source)) {
            this["ReplacedFiles"] = [];
        }
        if (!("CreatedDirectories" in $$source)) {
            this["CreatedDirectories"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppliedOperationManifest instance from a string or object.
     */
    static createFrom($$source: any = {}): AppliedOperationManifest {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("AddedFiles" in $$parsedSource) {
            $$parsedSource["AddedFiles"] = $$createField0_0($$parsedSource["AddedFiles"]);
        }
        if ("ReplacedFiles" in $$parsedSource) {
            $$parsedSource["ReplacedFiles"] = $$createField1_0($$parsedSource["ReplacedFiles"]);
        }
        if ("CreatedDirectories" in $$parsedSource) {
            $$parsedSource["CreatedDirectories"] = $$createField2_0($$parsedSource["CreatedDirectories"]);
        }
        return new AppliedOperationManifest($$parsedSource as Partial<AppliedOperationManifest>);
    }
}

export class AppliedProfileSummary {
    "GameID": number;
    "ProfileID": number;
    "ProfileName": string;
    "AppliedAt": string;
    "HasAppliedProfileChanged": boolean | null;

    /** Creates a new AppliedProfileSummary instance. */
    constructor($$source: Partial<AppliedProfileSummary> = {}) {
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("ProfileID" in $$source)) {
            this["ProfileID"] = 0;
        }
        if (!("ProfileName" in $$source)) {
            this["ProfileName"] = "";
        }
        if (!("AppliedAt" in $$source)) {
            this["AppliedAt"] = "";
        }
        if (!("HasAppliedProfileChanged" in $$source)) {
            this["HasAppliedProfileChanged"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppliedProfileSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): AppliedProfileSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppliedProfileSummary($$parsedSource as Partial<AppliedProfileSummary>);
    }
}

export class ApplyOperationPlanResult {
    "Success": boolean;
    "CompletedCount": number;
    "FailedCount": number;
    "SkippedCount": number;
    "Results": ApplyOperationResult[];
    "Manifest": AppliedOperationManifest;

    /** Creates a new ApplyOperationPlanResult instance. */
    constructor($$source: Partial<ApplyOperationPlanResult> = {}) {
        if (!("Success" in $$source)) {
            this["Success"] = false;
        }
        if (!("CompletedCount" in $$source)) {
            this["CompletedCount"] = 0;
        }
        if (!("FailedCount" in $$source)) {
            this["FailedCount"] = 0;
        }
        if (!("SkippedCount" in $$source)) {
            this["SkippedCount"] = 0;
        }
        if (!("Results" in $$source)) {
            this["Results"] = [];
        }
        if (!("Manifest" in $$source)) {
            this["Manifest"] = (new AppliedOperationManifest());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplyOperationPlanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ApplyOperationPlanResult {
        const $$createField4_0 = $$createType8;
        const $$createField5_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Results" in $$parsedSource) {
            $$parsedSource["Results"] = $$createField4_0($$parsedSource["Results"]);
        }
        if ("Manifest" in $$parsedSource) {
            $$parsedSource["Manifest"] = $$createField5_0($$parsedSource["Manifest"]);
        }
        return new ApplyOperationPlanResult($$parsedSource as Partial<ApplyOperationPlanResult>);
    }
}

export class ApplyOperationResult {
    "OperationIndex": number;
    "Operation": Operation;
    "Status": ApplyOperationStatus;
    "Message": string;
    "Error": string | null;

    /** Creates a new ApplyOperationResult instance. */
    constructor($$source: Partial<ApplyOperationResult> = {}) {
        if (!("OperationIndex" in $$source)) {
            this["OperationIndex"] = 0;
        }
        if (!("Operation" in $$source)) {
            this["Operation"] = (new Operation());
        }
        if (!("Status" in $$source)) {
            this["Status"] = ApplyOperationStatus.$zero;
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }
        if (!("Error" in $$source)) {
            this["Error"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplyOperationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ApplyOperationResult {
        const $$createField1_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Operation" in $$parsedSource) {
            $$parsedSource["Operation"] = $$createField1_0($$parsedSource["Operation"]);
        }
        return new ApplyOperationResult($$parsedSource as Partial<ApplyOperationResult>);
    }
}

export enum ApplyOperationStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ApplyOperationStatusCompleted = "completed",
    ApplyOperationStatusFailed = "failed",
    ApplyOperationStatusSkipped = "skipped",
};

export class DiagnosticLogEntry {
    "Timestamp": string;
    "Level": string;
    "Operation": string;
    "Message": string;
    "Details": { [_ in string]?: string };

    /** Creates a new DiagnosticLogEntry instance. */
    constructor($$source: Partial<DiagnosticLogEntry> = {}) {
        if (!("Timestamp" in $$source)) {
            this["Timestamp"] = "";
        }
        if (!("Level" in $$source)) {
            this["Level"] = "";
        }
        if (!("Operation" in $$source)) {
            this["Operation"] = "";
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }
        if (!("Details" in $$source)) {
            this["Details"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticLogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): DiagnosticLogEntry {
        const $$createField4_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Details" in $$parsedSource) {
            $$parsedSource["Details"] = $$createField4_0($$parsedSource["Details"]);
        }
        return new DiagnosticLogEntry($$parsedSource as Partial<DiagnosticLogEntry>);
    }
}

export class ExportDiagnosticLogsInput {
    "Path": string;
    "Entries": DiagnosticLogEntry[];

    /** Creates a new ExportDiagnosticLogsInput instance. */
    constructor($$source: Partial<ExportDiagnosticLogsInput> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Entries" in $$source)) {
            this["Entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportDiagnosticLogsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportDiagnosticLogsInput {
        const $$createField1_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Entries" in $$parsedSource) {
            $$parsedSource["Entries"] = $$createField1_0($$parsedSource["Entries"]);
        }
        return new ExportDiagnosticLogsInput($$parsedSource as Partial<ExportDiagnosticLogsInput>);
    }
}

export class ImportModInput {
    "GameID": number;
    "Name": string;
    "SourceType": ModSourceType;
    "SourcePath": string;
    "StrategyType": StrategyType;
    "TargetRelativePath": string;

    /** Creates a new ImportModInput instance. */
    constructor($$source: Partial<ImportModInput> = {}) {
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("SourceType" in $$source)) {
            this["SourceType"] = ModSourceType.$zero;
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }
        if (!("StrategyType" in $$source)) {
            this["StrategyType"] = StrategyType.$zero;
        }
        if (!("TargetRelativePath" in $$source)) {
            this["TargetRelativePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportModInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportModInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportModInput($$parsedSource as Partial<ImportModInput>);
    }
}

export class ImportModResult {
    "Mod": Mod;
    "Config": ModInstallConfig;

    /** Creates a new ImportModResult instance. */
    constructor($$source: Partial<ImportModResult> = {}) {
        if (!("Mod" in $$source)) {
            this["Mod"] = (new Mod());
        }
        if (!("Config" in $$source)) {
            this["Config"] = (new ModInstallConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportModResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportModResult {
        const $$createField0_0 = $$createType14;
        const $$createField1_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mod" in $$parsedSource) {
            $$parsedSource["Mod"] = $$createField0_0($$parsedSource["Mod"]);
        }
        if ("Config" in $$parsedSource) {
            $$parsedSource["Config"] = $$createField1_0($$parsedSource["Config"]);
        }
        return new ImportModResult($$parsedSource as Partial<ImportModResult>);
    }
}

export class ListDiagnosticLogsInput {
    "Limit": number;
    "Operation": string;
    "Level": string;

    /** Creates a new ListDiagnosticLogsInput instance. */
    constructor($$source: Partial<ListDiagnosticLogsInput> = {}) {
        if (!("Limit" in $$source)) {
            this["Limit"] = 0;
        }
        if (!("Operation" in $$source)) {
            this["Operation"] = "";
        }
        if (!("Level" in $$source)) {
            this["Level"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListDiagnosticLogsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ListDiagnosticLogsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListDiagnosticLogsInput($$parsedSource as Partial<ListDiagnosticLogsInput>);
    }
}

export class Mod {
    "ID": number;
    "GameID": number;
    "Name": string;
    "SourceType": ModSourceType;
    "SourcePath": string;
    "OriginalSourcePath": string;
    "OriginalSourceName": string | null;
    "FileCount": number | null;
    "DirectoryCount": number | null;
    "TotalSizeBytes": number | null;
    "MetadataJSON": string | null;
    "CreatedAt": string;
    "UpdatedAt": string;

    /** Creates a new Mod instance. */
    constructor($$source: Partial<Mod> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("SourceType" in $$source)) {
            this["SourceType"] = ModSourceType.$zero;
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }
        if (!("OriginalSourcePath" in $$source)) {
            this["OriginalSourcePath"] = "";
        }
        if (!("OriginalSourceName" in $$source)) {
            this["OriginalSourceName"] = null;
        }
        if (!("FileCount" in $$source)) {
            this["FileCount"] = null;
        }
        if (!("DirectoryCount" in $$source)) {
            this["DirectoryCount"] = null;
        }
        if (!("TotalSizeBytes" in $$source)) {
            this["TotalSizeBytes"] = null;
        }
        if (!("MetadataJSON" in $$source)) {
            this["MetadataJSON"] = null;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = "";
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Mod instance from a string or object.
     */
    static createFrom($$source: any = {}): Mod {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Mod($$parsedSource as Partial<Mod>);
    }
}

export class ModContext {
    "ModID": number;
    "ModName": string;

    /** Creates a new ModContext instance. */
    constructor($$source: Partial<ModContext> = {}) {
        if (!("ModID" in $$source)) {
            this["ModID"] = 0;
        }
        if (!("ModName" in $$source)) {
            this["ModName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModContext instance from a string or object.
     */
    static createFrom($$source: any = {}): ModContext {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModContext($$parsedSource as Partial<ModContext>);
    }
}

export class ModDeleteSummary {
    "ModID": number;
    "ModName": string;
    "ProfileUsageCount": number;
    "IsInAppliedProfile": boolean;
    "ManagedSourcePath": string;
    "OriginalSourceName": string | null;
    "OriginalSourcePath": string;

    /** Creates a new ModDeleteSummary instance. */
    constructor($$source: Partial<ModDeleteSummary> = {}) {
        if (!("ModID" in $$source)) {
            this["ModID"] = 0;
        }
        if (!("ModName" in $$source)) {
            this["ModName"] = "";
        }
        if (!("ProfileUsageCount" in $$source)) {
            this["ProfileUsageCount"] = 0;
        }
        if (!("IsInAppliedProfile" in $$source)) {
            this["IsInAppliedProfile"] = false;
        }
        if (!("ManagedSourcePath" in $$source)) {
            this["ManagedSourcePath"] = "";
        }
        if (!("OriginalSourceName" in $$source)) {
            this["OriginalSourceName"] = null;
        }
        if (!("OriginalSourcePath" in $$source)) {
            this["OriginalSourcePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModDeleteSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ModDeleteSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModDeleteSummary($$parsedSource as Partial<ModDeleteSummary>);
    }
}

export class ModInstallConfig {
    "ModID": number;
    "StrategyType": string;
    "TargetBase": string;
    "TargetRelativePath": string;
    "SourceSubpath": string | null;
    "CreatedAt": string;
    "UpdatedAt": string;

    /** Creates a new ModInstallConfig instance. */
    constructor($$source: Partial<ModInstallConfig> = {}) {
        if (!("ModID" in $$source)) {
            this["ModID"] = 0;
        }
        if (!("StrategyType" in $$source)) {
            this["StrategyType"] = "";
        }
        if (!("TargetBase" in $$source)) {
            this["TargetBase"] = "";
        }
        if (!("TargetRelativePath" in $$source)) {
            this["TargetRelativePath"] = "";
        }
        if (!("SourceSubpath" in $$source)) {
            this["SourceSubpath"] = null;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = "";
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModInstallConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ModInstallConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModInstallConfig($$parsedSource as Partial<ModInstallConfig>);
    }
}

export class ModProfile {
    "ID": number;
    "GameID": number;
    "Name": string;
    "CreatedAt": string;
    "UpdatedAt": string;

    /** Creates a new ModProfile instance. */
    constructor($$source: Partial<ModProfile> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = "";
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): ModProfile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModProfile($$parsedSource as Partial<ModProfile>);
    }
}

export enum ModSourceType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ModSourceTypeFolder = "folder",
    ModSourceTypeArchive = "archive",
};

export class Operation {
    "Type": OperationType;
    "SourcePath": string | null;
    "TargetPath": string;
    "BackupPath": string | null;
    "Conflict": boolean;
    "Mod": ModContext;

    /** Creates a new Operation instance. */
    constructor($$source: Partial<Operation> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = OperationType.$zero;
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = null;
        }
        if (!("TargetPath" in $$source)) {
            this["TargetPath"] = "";
        }
        if (!("BackupPath" in $$source)) {
            this["BackupPath"] = null;
        }
        if (!("Conflict" in $$source)) {
            this["Conflict"] = false;
        }
        if (!("Mod" in $$source)) {
            this["Mod"] = (new ModContext());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Operation instance from a string or object.
     */
    static createFrom($$source: any = {}): Operation {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mod" in $$parsedSource) {
            $$parsedSource["Mod"] = $$createField5_0($$parsedSource["Mod"]);
        }
        return new Operation($$parsedSource as Partial<Operation>);
    }
}

export class OperationPlan {
    "Operations": Operation[];
    "Issues": PlanIssue[];
    "CanApply": boolean;

    /** Creates a new OperationPlan instance. */
    constructor($$source: Partial<OperationPlan> = {}) {
        if (!("Operations" in $$source)) {
            this["Operations"] = [];
        }
        if (!("Issues" in $$source)) {
            this["Issues"] = [];
        }
        if (!("CanApply" in $$source)) {
            this["CanApply"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OperationPlan instance from a string or object.
     */
    static createFrom($$source: any = {}): OperationPlan {
        const $$createField0_0 = $$createType16;
        const $$createField1_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Operations" in $$parsedSource) {
            $$parsedSource["Operations"] = $$createField0_0($$parsedSource["Operations"]);
        }
        if ("Issues" in $$parsedSource) {
            $$parsedSource["Issues"] = $$createField1_0($$parsedSource["Issues"]);
        }
        return new OperationPlan($$parsedSource as Partial<OperationPlan>);
    }
}

export enum OperationType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OperationTypeCopy = "copy",
    OperationTypeReplace = "replace",
    OperationTypeCreateDirectory = "create_directory",
};

export class PlanIssue {
    "Severity": PlanIssueSeverity;
    "Kind": PlanIssueKind;
    "Message": string;
    "ProfileID": number;
    "SourcePath": string | null;
    "TargetPath": string | null;
    "Mod": ModContext | null;
    "ConflictingOperationIndexes": number[];

    /** Creates a new PlanIssue instance. */
    constructor($$source: Partial<PlanIssue> = {}) {
        if (!("Severity" in $$source)) {
            this["Severity"] = PlanIssueSeverity.$zero;
        }
        if (!("Kind" in $$source)) {
            this["Kind"] = PlanIssueKind.$zero;
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }
        if (!("ProfileID" in $$source)) {
            this["ProfileID"] = 0;
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = null;
        }
        if (!("TargetPath" in $$source)) {
            this["TargetPath"] = null;
        }
        if (!("Mod" in $$source)) {
            this["Mod"] = null;
        }
        if (!("ConflictingOperationIndexes" in $$source)) {
            this["ConflictingOperationIndexes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlanIssue instance from a string or object.
     */
    static createFrom($$source: any = {}): PlanIssue {
        const $$createField6_0 = $$createType19;
        const $$createField7_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mod" in $$parsedSource) {
            $$parsedSource["Mod"] = $$createField6_0($$parsedSource["Mod"]);
        }
        if ("ConflictingOperationIndexes" in $$parsedSource) {
            $$parsedSource["ConflictingOperationIndexes"] = $$createField7_0($$parsedSource["ConflictingOperationIndexes"]);
        }
        return new PlanIssue($$parsedSource as Partial<PlanIssue>);
    }
}

export enum PlanIssueKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PlanIssueMissingManagedSourcePath = "missing_managed_source_path",
    PlanIssueMissingInstallConfig = "missing_install_config",
    PlanIssueIncompleteInstallConfig = "incomplete_install_config",
    PlanIssueMissingGameInstallPath = "missing_game_install_path",
    PlanIssueMissingGameInstallDir = "missing_game_install_directory",
    PlanIssueGameInstallPathNotDir = "game_install_path_not_directory",
    PlanIssueMissingSourceRoot = "missing_source_root",
    PlanIssueSourceRootNotDirectory = "source_root_not_directory",
    PlanIssueMissingGameModStorage = "missing_game_mod_storage_path",
    PlanIssueTargetDirectoryPathFile = "target_directory_path_is_file",
    PlanIssueTargetFilePathDirectory = "target_file_path_is_directory",
    PlanIssueTargetPathConflict = "target_path_conflict",
    PlanIssueReplaceExistingTarget = "replace_existing_target",
};

export enum PlanIssueSeverity {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PlanIssueSeverityError = "error",
    PlanIssueSeverityWarning = "warning",
};

export class PreValidateImportInput {
    "SourceType": ModSourceType;
    "SourcePath": string;

    /** Creates a new PreValidateImportInput instance. */
    constructor($$source: Partial<PreValidateImportInput> = {}) {
        if (!("SourceType" in $$source)) {
            this["SourceType"] = ModSourceType.$zero;
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreValidateImportInput instance from a string or object.
     */
    static createFrom($$source: any = {}): PreValidateImportInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PreValidateImportInput($$parsedSource as Partial<PreValidateImportInput>);
    }
}

export class Preview {
    "StrategyType": StrategyType;
    "TargetBase": string;
    "TargetRelativePath": string;
    "TargetDisplayPath": string;
    "TotalFileCount": number;
    "TotalDirectoryCount": number;
    "TotalSizeBytes": number;
    "TargetFilePaths": string[];
    "IsCapped": boolean;
    "Cap": number;
    "Warnings": string[];

    /** Creates a new Preview instance. */
    constructor($$source: Partial<Preview> = {}) {
        if (!("StrategyType" in $$source)) {
            this["StrategyType"] = StrategyType.$zero;
        }
        if (!("TargetBase" in $$source)) {
            this["TargetBase"] = "";
        }
        if (!("TargetRelativePath" in $$source)) {
            this["TargetRelativePath"] = "";
        }
        if (!("TargetDisplayPath" in $$source)) {
            this["TargetDisplayPath"] = "";
        }
        if (!("TotalFileCount" in $$source)) {
            this["TotalFileCount"] = 0;
        }
        if (!("TotalDirectoryCount" in $$source)) {
            this["TotalDirectoryCount"] = 0;
        }
        if (!("TotalSizeBytes" in $$source)) {
            this["TotalSizeBytes"] = 0;
        }
        if (!("TargetFilePaths" in $$source)) {
            this["TargetFilePaths"] = [];
        }
        if (!("IsCapped" in $$source)) {
            this["IsCapped"] = false;
        }
        if (!("Cap" in $$source)) {
            this["Cap"] = 0;
        }
        if (!("Warnings" in $$source)) {
            this["Warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preview instance from a string or object.
     */
    static createFrom($$source: any = {}): Preview {
        const $$createField7_0 = $$createType21;
        const $$createField10_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("TargetFilePaths" in $$parsedSource) {
            $$parsedSource["TargetFilePaths"] = $$createField7_0($$parsedSource["TargetFilePaths"]);
        }
        if ("Warnings" in $$parsedSource) {
            $$parsedSource["Warnings"] = $$createField10_0($$parsedSource["Warnings"]);
        }
        return new Preview($$parsedSource as Partial<Preview>);
    }
}

export class PreviewImportConfigurationInput {
    "GameID": number;
    "SourceType": ModSourceType;
    "SourcePath": string;
    "StrategyType": StrategyType;
    "TargetRelativePath": string;

    /** Creates a new PreviewImportConfigurationInput instance. */
    constructor($$source: Partial<PreviewImportConfigurationInput> = {}) {
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("SourceType" in $$source)) {
            this["SourceType"] = ModSourceType.$zero;
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }
        if (!("StrategyType" in $$source)) {
            this["StrategyType"] = StrategyType.$zero;
        }
        if (!("TargetRelativePath" in $$source)) {
            this["TargetRelativePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewImportConfigurationInput instance from a string or object.
     */
    static createFrom($$source: any = {}): PreviewImportConfigurationInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PreviewImportConfigurationInput($$parsedSource as Partial<PreviewImportConfigurationInput>);
    }
}

export class ProfileMod {
    "ProfileID": number;
    "ModID": number;
    "Name": string;
    "SourcePath": string;
    "Enabled": boolean;
    "LoadOrder": number;
    "CreatedAt": string;
    "UpdatedAt": string;

    /** Creates a new ProfileMod instance. */
    constructor($$source: Partial<ProfileMod> = {}) {
        if (!("ProfileID" in $$source)) {
            this["ProfileID"] = 0;
        }
        if (!("ModID" in $$source)) {
            this["ModID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }
        if (!("Enabled" in $$source)) {
            this["Enabled"] = false;
        }
        if (!("LoadOrder" in $$source)) {
            this["LoadOrder"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = "";
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileMod instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileMod {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileMod($$parsedSource as Partial<ProfileMod>);
    }
}

export class ReShadeDetectionResult {
    "Status": ReShadeDetectionStatus;
    "Targets": ReShadeTarget[];
    "UnsupportedReason": string | null;

    /** Creates a new ReShadeDetectionResult instance. */
    constructor($$source: Partial<ReShadeDetectionResult> = {}) {
        if (!("Status" in $$source)) {
            this["Status"] = ReShadeDetectionStatus.$zero;
        }
        if (!("Targets" in $$source)) {
            this["Targets"] = [];
        }
        if (!("UnsupportedReason" in $$source)) {
            this["UnsupportedReason"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReShadeDetectionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ReShadeDetectionResult {
        const $$createField1_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Targets" in $$parsedSource) {
            $$parsedSource["Targets"] = $$createField1_0($$parsedSource["Targets"]);
        }
        return new ReShadeDetectionResult($$parsedSource as Partial<ReShadeDetectionResult>);
    }
}

export enum ReShadeDetectionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ReShadeDetectionStatusInstalled = "installed",
    ReShadeDetectionStatusNotInstalled = "not_installed",
    ReShadeDetectionStatusUnsupported = "unsupported",
};

export class ReShadeTarget {
    "Path": string;
    "Executables": string[];

    /** Creates a new ReShadeTarget instance. */
    constructor($$source: Partial<ReShadeTarget> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Executables" in $$source)) {
            this["Executables"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReShadeTarget instance from a string or object.
     */
    static createFrom($$source: any = {}): ReShadeTarget {
        const $$createField1_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Executables" in $$parsedSource) {
            $$parsedSource["Executables"] = $$createField1_0($$parsedSource["Executables"]);
        }
        return new ReShadeTarget($$parsedSource as Partial<ReShadeTarget>);
    }
}

export class ReplacedFileManifestEntry {
    "OperationIndex": number;
    "Mod": ModContext;
    "SourcePath": string;
    "TargetPath": string;
    "SHA256": string;
    "SizeBytes": number;
    "BackupPath": string;
    "BackupSHA256": string;
    "BackupSizeBytes": number;

    /** Creates a new ReplacedFileManifestEntry instance. */
    constructor($$source: Partial<ReplacedFileManifestEntry> = {}) {
        if (!("OperationIndex" in $$source)) {
            this["OperationIndex"] = 0;
        }
        if (!("Mod" in $$source)) {
            this["Mod"] = (new ModContext());
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }
        if (!("TargetPath" in $$source)) {
            this["TargetPath"] = "";
        }
        if (!("SHA256" in $$source)) {
            this["SHA256"] = "";
        }
        if (!("SizeBytes" in $$source)) {
            this["SizeBytes"] = 0;
        }
        if (!("BackupPath" in $$source)) {
            this["BackupPath"] = "";
        }
        if (!("BackupSHA256" in $$source)) {
            this["BackupSHA256"] = "";
        }
        if (!("BackupSizeBytes" in $$source)) {
            this["BackupSizeBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReplacedFileManifestEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ReplacedFileManifestEntry {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mod" in $$parsedSource) {
            $$parsedSource["Mod"] = $$createField1_0($$parsedSource["Mod"]);
        }
        return new ReplacedFileManifestEntry($$parsedSource as Partial<ReplacedFileManifestEntry>);
    }
}

export class RestoreMod {
    "ID": number;
    "Name": string;

    /** Creates a new RestoreMod instance. */
    constructor($$source: Partial<RestoreMod> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestoreMod instance from a string or object.
     */
    static createFrom($$source: any = {}): RestoreMod {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RestoreMod($$parsedSource as Partial<RestoreMod>);
    }
}

export class RestoreOperation {
    "Type": RestoreOperationType;
    "ManifestOperationIndex": number;
    "Mod": RestoreMod;
    "TargetPath": string;
    "BackupPath": string | null;

    /** Creates a new RestoreOperation instance. */
    constructor($$source: Partial<RestoreOperation> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = RestoreOperationType.$zero;
        }
        if (!("ManifestOperationIndex" in $$source)) {
            this["ManifestOperationIndex"] = 0;
        }
        if (!("Mod" in $$source)) {
            this["Mod"] = (new RestoreMod());
        }
        if (!("TargetPath" in $$source)) {
            this["TargetPath"] = "";
        }
        if (!("BackupPath" in $$source)) {
            this["BackupPath"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestoreOperation instance from a string or object.
     */
    static createFrom($$source: any = {}): RestoreOperation {
        const $$createField2_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mod" in $$parsedSource) {
            $$parsedSource["Mod"] = $$createField2_0($$parsedSource["Mod"]);
        }
        return new RestoreOperation($$parsedSource as Partial<RestoreOperation>);
    }
}

export class RestoreOperationResult {
    "OperationIndex": number;
    "Operation": RestoreOperation;
    "Status": RestoreOperationStatus;
    "Message": string;
    "Error": string | null;

    /** Creates a new RestoreOperationResult instance. */
    constructor($$source: Partial<RestoreOperationResult> = {}) {
        if (!("OperationIndex" in $$source)) {
            this["OperationIndex"] = 0;
        }
        if (!("Operation" in $$source)) {
            this["Operation"] = (new RestoreOperation());
        }
        if (!("Status" in $$source)) {
            this["Status"] = RestoreOperationStatus.$zero;
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }
        if (!("Error" in $$source)) {
            this["Error"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestoreOperationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RestoreOperationResult {
        const $$createField1_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Operation" in $$parsedSource) {
            $$parsedSource["Operation"] = $$createField1_0($$parsedSource["Operation"]);
        }
        return new RestoreOperationResult($$parsedSource as Partial<RestoreOperationResult>);
    }
}

export enum RestoreOperationStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RestoreOperationStatusCompleted = "completed",
    RestoreOperationStatusFailed = "failed",
    RestoreOperationStatusSkipped = "skipped",
};

export enum RestoreOperationType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RestoreOperationTypeRemoveAddedFile = "remove_added_file",
    RestoreOperationTypeRestoreReplacedFile = "restore_replaced_file",
    RestoreOperationTypeRemoveCreatedDir = "remove_created_directory",
    RestoreOperationTypeDeleteRestoredBackup = "delete_restored_backup",
};

export class RestoreResult {
    "Success": boolean;
    "CompletedCount": number;
    "FailedCount": number;
    "SkippedCount": number;
    "Results": RestoreOperationResult[];

    /** Creates a new RestoreResult instance. */
    constructor($$source: Partial<RestoreResult> = {}) {
        if (!("Success" in $$source)) {
            this["Success"] = false;
        }
        if (!("CompletedCount" in $$source)) {
            this["CompletedCount"] = 0;
        }
        if (!("FailedCount" in $$source)) {
            this["FailedCount"] = 0;
        }
        if (!("SkippedCount" in $$source)) {
            this["SkippedCount"] = 0;
        }
        if (!("Results" in $$source)) {
            this["Results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestoreResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RestoreResult {
        const $$createField4_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Results" in $$parsedSource) {
            $$parsedSource["Results"] = $$createField4_0($$parsedSource["Results"]);
        }
        return new RestoreResult($$parsedSource as Partial<RestoreResult>);
    }
}

export class SourceScanResult {
    "Inserted": number;
    "Updated": number;
    "MarkedUnavailable": number;
    "Games": StoredGame[];

    /** Creates a new SourceScanResult instance. */
    constructor($$source: Partial<SourceScanResult> = {}) {
        if (!("Inserted" in $$source)) {
            this["Inserted"] = 0;
        }
        if (!("Updated" in $$source)) {
            this["Updated"] = 0;
        }
        if (!("MarkedUnavailable" in $$source)) {
            this["MarkedUnavailable"] = 0;
        }
        if (!("Games" in $$source)) {
            this["Games"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceScanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SourceScanResult {
        const $$createField3_0 = $$createType29;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Games" in $$parsedSource) {
            $$parsedSource["Games"] = $$createField3_0($$parsedSource["Games"]);
        }
        return new SourceScanResult($$parsedSource as Partial<SourceScanResult>);
    }
}

export class StoredGame {
    "ID": number;
    "Name": string;
    "InstallPath": string;
    "Source": string;
    "SourceID": string | null;
    "Available": boolean;
    "LastSeenAt": string | null;
    "ModStoragePath": string | null;
    "ModStoragePathOverride": string | null;

    /** Creates a new StoredGame instance. */
    constructor($$source: Partial<StoredGame> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("InstallPath" in $$source)) {
            this["InstallPath"] = "";
        }
        if (!("Source" in $$source)) {
            this["Source"] = "";
        }
        if (!("SourceID" in $$source)) {
            this["SourceID"] = null;
        }
        if (!("Available" in $$source)) {
            this["Available"] = false;
        }
        if (!("LastSeenAt" in $$source)) {
            this["LastSeenAt"] = null;
        }
        if (!("ModStoragePath" in $$source)) {
            this["ModStoragePath"] = null;
        }
        if (!("ModStoragePathOverride" in $$source)) {
            this["ModStoragePathOverride"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StoredGame instance from a string or object.
     */
    static createFrom($$source: any = {}): StoredGame {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StoredGame($$parsedSource as Partial<StoredGame>);
    }
}

export class StrategyDescriptor {
    "Type": StrategyType;
    "Label": string;
    "Description": string;
    "Visibility": StrategyVisibility;
    "RequiresTargetPath": boolean;

    /** Creates a new StrategyDescriptor instance. */
    constructor($$source: Partial<StrategyDescriptor> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = StrategyType.$zero;
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("Visibility" in $$source)) {
            this["Visibility"] = StrategyVisibility.$zero;
        }
        if (!("RequiresTargetPath" in $$source)) {
            this["RequiresTargetPath"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StrategyDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): StrategyDescriptor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StrategyDescriptor($$parsedSource as Partial<StrategyDescriptor>);
    }
}

export enum StrategyType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StrategyTypeGenericCopy = "generic_copy",
    StrategyTypeBepInEx = "bepinex",
    StrategyTypeUnrealPak = "unreal_pak",
};

export enum StrategyVisibility {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StrategyVisibilitySelectable = "selectable",
    StrategyVisibilityDisabled = "disabled",
    StrategyVisibilityInternal = "internal",
};

// Private type creation functions
const $$createType0 = ModContext.createFrom;
const $$createType1 = AppliedFileManifestEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ReplacedFileManifestEntry.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = AppliedDirectoryManifestEntry.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = ApplyOperationResult.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = AppliedOperationManifest.createFrom;
const $$createType10 = Operation.createFrom;
const $$createType11 = $Create.Map($Create.Any, $Create.Any);
const $$createType12 = DiagnosticLogEntry.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = Mod.createFrom;
const $$createType15 = ModInstallConfig.createFrom;
const $$createType16 = $Create.Array($$createType10);
const $$createType17 = PlanIssue.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $Create.Nullable($$createType0);
const $$createType20 = $Create.Array($Create.Any);
const $$createType21 = $Create.Array($Create.Any);
const $$createType22 = ReShadeTarget.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = RestoreMod.createFrom;
const $$createType25 = RestoreOperation.createFrom;
const $$createType26 = RestoreOperationResult.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = StoredGame.createFrom;
const $$createType29 = $Create.Array($$createType28);
