// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum ConflictCategory {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ConflictExpectedOverwrite = "expected_overwrite",
    ConflictAmbiguousOverwrite = "ambiguous_overwrite",
    ConflictDestructiveFileDirectory = "destructive_file_directory",
};

export class DesiredFile {
    "GameRelativePath": string;
    "SourcePath": string;
    "SHA256": string;
    "SizeBytes": number;
    "OutputKind": OutputKind;
    "Winner": WriterEntry;
    "Writers": WriterEntry[];
    "ConflictCategory": ConflictCategory;
    "FileStatus": FileStatus;
    "RiskLevel": RiskLevel;
    "Explanation": string;

    /** Creates a new DesiredFile instance. */
    constructor($$source: Partial<DesiredFile> = {}) {
        if (!("GameRelativePath" in $$source)) {
            this["GameRelativePath"] = "";
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }
        if (!("SHA256" in $$source)) {
            this["SHA256"] = "";
        }
        if (!("SizeBytes" in $$source)) {
            this["SizeBytes"] = 0;
        }
        if (!("OutputKind" in $$source)) {
            this["OutputKind"] = OutputKind.$zero;
        }
        if (!("Winner" in $$source)) {
            this["Winner"] = (new WriterEntry());
        }
        if (!("Writers" in $$source)) {
            this["Writers"] = [];
        }
        if (!("ConflictCategory" in $$source)) {
            this["ConflictCategory"] = ConflictCategory.$zero;
        }
        if (!("FileStatus" in $$source)) {
            this["FileStatus"] = FileStatus.$zero;
        }
        if (!("RiskLevel" in $$source)) {
            this["RiskLevel"] = RiskLevel.$zero;
        }
        if (!("Explanation" in $$source)) {
            this["Explanation"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesiredFile instance from a string or object.
     */
    static createFrom($$source: any = {}): DesiredFile {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Winner" in $$parsedSource) {
            $$parsedSource["Winner"] = $$createField5_0($$parsedSource["Winner"]);
        }
        if ("Writers" in $$parsedSource) {
            $$parsedSource["Writers"] = $$createField6_0($$parsedSource["Writers"]);
        }
        return new DesiredFile($$parsedSource as Partial<DesiredFile>);
    }
}

export class DesiredState {
    "ProfileID": number;
    "GameID": number;
    "Files": { [_ in string]?: DesiredFile };
    "Issues": PlanIssue[];

    /** Creates a new DesiredState instance. */
    constructor($$source: Partial<DesiredState> = {}) {
        if (!("ProfileID" in $$source)) {
            this["ProfileID"] = 0;
        }
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("Files" in $$source)) {
            this["Files"] = {};
        }
        if (!("Issues" in $$source)) {
            this["Issues"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesiredState instance from a string or object.
     */
    static createFrom($$source: any = {}): DesiredState {
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Files" in $$parsedSource) {
            $$parsedSource["Files"] = $$createField2_0($$parsedSource["Files"]);
        }
        if ("Issues" in $$parsedSource) {
            $$parsedSource["Issues"] = $$createField3_0($$parsedSource["Issues"]);
        }
        return new DesiredState($$parsedSource as Partial<DesiredState>);
    }
}

export enum DriftKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DriftNone = "none",
    DriftMissing = "missing",
    DriftModified = "modified",
    DriftExternal = "external",
};

export enum FileStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FileStatusAdded = "added",
    FileStatusReplaced = "replaced",
    FileStatusDeleted = "deleted",
    FileStatusRestored = "restored",
    FileStatusBlocked = "blocked",
    FileStatusConflict = "conflict",
    FileStatusDrifted = "drifted",
    FileStatusExternal = "external",
    FileStatusSkipped = "skipped",
    FileStatusUnchanged = "unchanged",
};

export class ModContext {
    "ModID": number;
    "ModName": string;

    /** Creates a new ModContext instance. */
    constructor($$source: Partial<ModContext> = {}) {
        if (!("ModID" in $$source)) {
            this["ModID"] = 0;
        }
        if (!("ModName" in $$source)) {
            this["ModName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModContext instance from a string or object.
     */
    static createFrom($$source: any = {}): ModContext {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModContext($$parsedSource as Partial<ModContext>);
    }
}

export enum OutputKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OutputCopied = "copied",
};

export class PlanIssue {
    "Severity": PlanIssueSeverity;
    "Kind": PlanIssueKind;
    "Message": string;
    "ProfileID": number;
    "SourcePath": string | null;
    "TargetPath": string | null;
    "Mod": ModContext | null;

    /** Creates a new PlanIssue instance. */
    constructor($$source: Partial<PlanIssue> = {}) {
        if (!("Severity" in $$source)) {
            this["Severity"] = PlanIssueSeverity.$zero;
        }
        if (!("Kind" in $$source)) {
            this["Kind"] = PlanIssueKind.$zero;
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }
        if (!("ProfileID" in $$source)) {
            this["ProfileID"] = 0;
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = null;
        }
        if (!("TargetPath" in $$source)) {
            this["TargetPath"] = null;
        }
        if (!("Mod" in $$source)) {
            this["Mod"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlanIssue instance from a string or object.
     */
    static createFrom($$source: any = {}): PlanIssue {
        const $$createField6_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mod" in $$parsedSource) {
            $$parsedSource["Mod"] = $$createField6_0($$parsedSource["Mod"]);
        }
        return new PlanIssue($$parsedSource as Partial<PlanIssue>);
    }
}

export enum PlanIssueKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PlanIssueMissingManagedSourcePath = "missing_managed_source_path",
    PlanIssueMissingInstallConfig = "missing_install_config",
    PlanIssueIncompleteInstallConfig = "incomplete_install_config",
    PlanIssueMissingSourceRoot = "missing_source_root",
    PlanIssueSourceRootNotDirectory = "source_root_not_directory",
    PlanIssueInvalidUnrealPakSource = "invalid_unreal_pak_source",
    PlanIssueUnsupportedStrategy = "unsupported_strategy",
};

export enum PlanIssueSeverity {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PlanIssueSeverityError = "error",
    PlanIssueSeverityWarning = "warning",
};

export enum RiskLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RiskNone = "none",
    RiskInfo = "info",
    RiskError = "error",
};

export enum SourceKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SourceKindBaseGame = "base_game",
    SourceKindMod = "mod",
};

export class WriterEntry {
    "Order": number;
    "SourceKind": SourceKind;
    "SourceID": string;
    "ModID": number | null;
    "ModName": string;
    "LoadOrder": number;
    "IsWinner": boolean;
    "WouldWrite": boolean;

    /** Creates a new WriterEntry instance. */
    constructor($$source: Partial<WriterEntry> = {}) {
        if (!("Order" in $$source)) {
            this["Order"] = 0;
        }
        if (!("SourceKind" in $$source)) {
            this["SourceKind"] = SourceKind.$zero;
        }
        if (!("SourceID" in $$source)) {
            this["SourceID"] = "";
        }
        if (!("ModID" in $$source)) {
            this["ModID"] = null;
        }
        if (!("ModName" in $$source)) {
            this["ModName"] = "";
        }
        if (!("LoadOrder" in $$source)) {
            this["LoadOrder"] = 0;
        }
        if (!("IsWinner" in $$source)) {
            this["IsWinner"] = false;
        }
        if (!("WouldWrite" in $$source)) {
            this["WouldWrite"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WriterEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): WriterEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WriterEntry($$parsedSource as Partial<WriterEntry>);
    }
}

// Private type creation functions
const $$createType0 = WriterEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = DesiredFile.createFrom;
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = PlanIssue.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = ModContext.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
