// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "./dto/models.js";

export function ExportLogs(input: dto$0.ExportDiagnosticLogsInput): $CancellablePromise<void> {
    return $Call.ByID(2264324867, input);
}

export function ListRecentLogs(input: dto$0.ListDiagnosticLogsInput): $CancellablePromise<dto$0.DiagnosticLogEntry[]> {
    return $Call.ByID(702039462, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListRecentRawLogs(input: dto$0.ListDiagnosticLogsInput): $CancellablePromise<string> {
    return $Call.ByID(693124794, input);
}

// Private type creation functions
const $$createType0 = dto$0.DiagnosticLogEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
