// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "./dto/models.js";

export function DetectGameReShade(gameID: number): $CancellablePromise<dto$0.ReShadeDetectionResult> {
    return $Call.ByID(1526227722, gameID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetStoredGames(): $CancellablePromise<dto$0.StoredGame[]> {
    return $Call.ByID(3350881315).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ScanAndSaveGames(): $CancellablePromise<dto$0.SourceScanResult> {
    return $Call.ByID(3143372107).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = dto$0.ReShadeDetectionResult.createFrom;
const $$createType1 = dto$0.StoredGame.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = dto$0.SourceScanResult.createFrom;
