// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DiagnosticsService from "./diagnosticsservice.js";
import * as GamesService from "./gamesservice.js";
import * as ModService from "./modservice.js";
import * as ProfileService from "./profileservice.js";
import * as SettingsService from "./settingsservice.js";
export {
    DiagnosticsService,
    GamesService,
    ModService,
    ProfileService,
    SettingsService
};
