// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as installconfig$0 from "../installconfig/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";

export class ImportConfiguredModInput {
    "GameID": number;
    "Name": string;
    "SourceType": storage$0.ModSourceType;
    "SourcePath": string;
    "StrategyType": installconfig$0.StrategyType;
    "TargetRelativePath": string;

    /** Creates a new ImportConfiguredModInput instance. */
    constructor($$source: Partial<ImportConfiguredModInput> = {}) {
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("SourceType" in $$source)) {
            this["SourceType"] = storage$0.ModSourceType.$zero;
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }
        if (!("StrategyType" in $$source)) {
            this["StrategyType"] = installconfig$0.StrategyType.$zero;
        }
        if (!("TargetRelativePath" in $$source)) {
            this["TargetRelativePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportConfiguredModInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportConfiguredModInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportConfiguredModInput($$parsedSource as Partial<ImportConfiguredModInput>);
    }
}

export class ImportConfiguredModResult {
    "Mod": storage$0.Mod;
    "Config": storage$0.ModInstallConfig;

    /** Creates a new ImportConfiguredModResult instance. */
    constructor($$source: Partial<ImportConfiguredModResult> = {}) {
        if (!("Mod" in $$source)) {
            this["Mod"] = (new storage$0.Mod());
        }
        if (!("Config" in $$source)) {
            this["Config"] = (new storage$0.ModInstallConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportConfiguredModResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportConfiguredModResult {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mod" in $$parsedSource) {
            $$parsedSource["Mod"] = $$createField0_0($$parsedSource["Mod"]);
        }
        if ("Config" in $$parsedSource) {
            $$parsedSource["Config"] = $$createField1_0($$parsedSource["Config"]);
        }
        return new ImportConfiguredModResult($$parsedSource as Partial<ImportConfiguredModResult>);
    }
}

export class PreviewImportConfigurationInput {
    "GameID": number;
    "SourceType": storage$0.ModSourceType;
    "SourcePath": string;
    "StrategyType": installconfig$0.StrategyType;
    "TargetRelativePath": string;

    /** Creates a new PreviewImportConfigurationInput instance. */
    constructor($$source: Partial<PreviewImportConfigurationInput> = {}) {
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("SourceType" in $$source)) {
            this["SourceType"] = storage$0.ModSourceType.$zero;
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }
        if (!("StrategyType" in $$source)) {
            this["StrategyType"] = installconfig$0.StrategyType.$zero;
        }
        if (!("TargetRelativePath" in $$source)) {
            this["TargetRelativePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewImportConfigurationInput instance from a string or object.
     */
    static createFrom($$source: any = {}): PreviewImportConfigurationInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PreviewImportConfigurationInput($$parsedSource as Partial<PreviewImportConfigurationInput>);
    }
}

// Private type creation functions
const $$createType0 = storage$0.Mod.createFrom;
const $$createType1 = storage$0.ModInstallConfig.createFrom;
