// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "./dto/models.js";

export function GetGameManagedModStorageUsage(gameID: number): $CancellablePromise<number> {
    return $Call.ByID(1476392311, gameID);
}

export function ImportMod(input: dto$0.ImportModInput): $CancellablePromise<dto$0.ImportModResult> {
    return $Call.ByID(2313069445, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListImportStrategies(): $CancellablePromise<dto$0.StrategyDescriptor[]> {
    return $Call.ByID(1013940886).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListMods(gameID: number): $CancellablePromise<dto$0.Mod[]> {
    return $Call.ByID(2000775995, gameID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function PreviewImportConfiguration(input: dto$0.PreviewImportConfigurationInput): $CancellablePromise<dto$0.Preview> {
    return $Call.ByID(1144919971, input).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = dto$0.ImportModResult.createFrom;
const $$createType1 = dto$0.StrategyDescriptor.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = dto$0.Mod.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = dto$0.Preview.createFrom;
