// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";

export function ImportModFolder(gameID: number, name: string, sourceFolderPath: string): $CancellablePromise<storage$0.Mod> {
    return $Call.ByID(2686117309, gameID, name, sourceFolderPath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListMods(gameID: number): $CancellablePromise<storage$0.Mod[]> {
    return $Call.ByID(2000775995, gameID).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = storage$0.Mod.createFrom;
const $$createType1 = $Create.Array($$createType0);
