// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";

export function ActivateProfile(gameID: number, profileID: number): $CancellablePromise<storage$0.ModProfile> {
    return $Call.ByID(1277552771, gameID, profileID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ClearActiveProfile(gameID: number): $CancellablePromise<void> {
    return $Call.ByID(576432483, gameID);
}

export function CreateProfile(gameID: number, name: string): $CancellablePromise<storage$0.ModProfile> {
    return $Call.ByID(4253656700, gameID, name).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DeleteProfile(profileID: number): $CancellablePromise<void> {
    return $Call.ByID(3036503493, profileID);
}

export function GetActiveProfile(gameID: number): $CancellablePromise<storage$0.ModProfile | null> {
    return $Call.ByID(4123009592, gameID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListProfiles(gameID: number): $CancellablePromise<storage$0.ModProfile[]> {
    return $Call.ByID(3489323205, gameID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function RenameProfile(profileID: number, name: string): $CancellablePromise<storage$0.ModProfile> {
    return $Call.ByID(1972408074, profileID, name).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = storage$0.ModProfile.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
