// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";

export function EnsureGameModStoragePath(gameID: number): $CancellablePromise<string> {
    return $Call.ByID(606713683, gameID);
}

export function GetGlobalModStorageRoot(): $CancellablePromise<string> {
    return $Call.ByID(956269605);
}

export function ResolveGameModStoragePath(gameID: number): $CancellablePromise<string> {
    return $Call.ByID(2190485991, gameID);
}

export function SetGameModStoragePathOverride(gameID: number, path: string): $CancellablePromise<storage$0.StoredGame> {
    return $Call.ByID(2381929503, gameID, path).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetGlobalModStorageRoot(path: string): $CancellablePromise<void> {
    return $Call.ByID(3589951673, path);
}

// Private type creation functions
const $$createType0 = storage$0.StoredGame.createFrom;
