// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as steam$0 from "../steam/models.js";

export function GetInstalledSteamGames(): $CancellablePromise<steam$0.Game[]> {
    return $Call.ByID(1666003703).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetSteamLibraries(): $CancellablePromise<string[]> {
    return $Call.ByID(749466789).then(($result: any) => {
        return $$createType2($result);
    });
}

export function LocateSteamInstallation(): $CancellablePromise<steam$0.SteamPaths | null> {
    return $Call.ByID(2274155108).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = steam$0.Game.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = steam$0.SteamPaths.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
