// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as steam$0 from "../steam/models.js";

export function LocateSteamInstallation(): $CancellablePromise<steam$0.SteamPaths | null> {
    return $Call.ByID(2274155108).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = steam$0.SteamPaths.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
