// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Game {
    "AppID": string;
    "Name": string;
    "InstallDir": string;
    "LibraryPath": string;
    "InstallPath": string;
    "ManifestPath": string;

    /** Creates a new Game instance. */
    constructor($$source: Partial<Game> = {}) {
        if (!("AppID" in $$source)) {
            this["AppID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("InstallDir" in $$source)) {
            this["InstallDir"] = "";
        }
        if (!("LibraryPath" in $$source)) {
            this["LibraryPath"] = "";
        }
        if (!("InstallPath" in $$source)) {
            this["InstallPath"] = "";
        }
        if (!("ManifestPath" in $$source)) {
            this["ManifestPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Game instance from a string or object.
     */
    static createFrom($$source: any = {}): Game {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Game($$parsedSource as Partial<Game>);
    }
}

export enum ImageType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ImageTypeLogo = "logo",
    ImageTypeBanner = "banner",
    ImageTypeHero = "hero",
};

export class SteamPaths {
    "Root": string;
    "SteamApps": string;
    "UserData": string;
    "LibraryVDF": string;
    "Artwork": string;

    /** Creates a new SteamPaths instance. */
    constructor($$source: Partial<SteamPaths> = {}) {
        if (!("Root" in $$source)) {
            this["Root"] = "";
        }
        if (!("SteamApps" in $$source)) {
            this["SteamApps"] = "";
        }
        if (!("UserData" in $$source)) {
            this["UserData"] = "";
        }
        if (!("LibraryVDF" in $$source)) {
            this["LibraryVDF"] = "";
        }
        if (!("Artwork" in $$source)) {
            this["Artwork"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SteamPaths instance from a string or object.
     */
    static createFrom($$source: any = {}): SteamPaths {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SteamPaths($$parsedSource as Partial<SteamPaths>);
    }
}
