// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as deployment$0 from "../models.js";

export class DeploymentPlan {
    "Mode": PlanMode;
    "Paths": { [_ in string]?: PathPlan };
    "Issues": deployment$0.PlanIssue[];

    /** Creates a new DeploymentPlan instance. */
    constructor($$source: Partial<DeploymentPlan> = {}) {
        if (!("Mode" in $$source)) {
            this["Mode"] = PlanMode.$zero;
        }
        if (!("Paths" in $$source)) {
            this["Paths"] = {};
        }
        if (!("Issues" in $$source)) {
            this["Issues"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeploymentPlan instance from a string or object.
     */
    static createFrom($$source: any = {}): DeploymentPlan {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Paths" in $$parsedSource) {
            $$parsedSource["Paths"] = $$createField1_0($$parsedSource["Paths"]);
        }
        if ("Issues" in $$parsedSource) {
            $$parsedSource["Issues"] = $$createField2_0($$parsedSource["Issues"]);
        }
        return new DeploymentPlan($$parsedSource as Partial<DeploymentPlan>);
    }
}

export class FileStateSnapshot {
    "Exists": boolean;
    "SHA256": string;
    "SizeBytes": number;
    "Label": string;

    /** Creates a new FileStateSnapshot instance. */
    constructor($$source: Partial<FileStateSnapshot> = {}) {
        if (!("Exists" in $$source)) {
            this["Exists"] = false;
        }
        if (!("SHA256" in $$source)) {
            this["SHA256"] = "";
        }
        if (!("SizeBytes" in $$source)) {
            this["SizeBytes"] = 0;
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileStateSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): FileStateSnapshot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileStateSnapshot($$parsedSource as Partial<FileStateSnapshot>);
    }
}

export class PathPlan {
    "GameRelativePath": string;
    "PlannedAction": ReapplyAction;
    "FileStatus": deployment$0.FileStatus;
    "RiskLevel": deployment$0.RiskLevel;
    "ConflictCategory": deployment$0.ConflictCategory;
    "DriftKind": deployment$0.DriftKind;
    "Baseline": FileStateSnapshot;
    "Applied": FileStateSnapshot;
    "Current": FileStateSnapshot;
    "Desired": FileStateSnapshot;
    "BaselineBackupPath": string;
    "LastAppliedAt": string;

    /** Creates a new PathPlan instance. */
    constructor($$source: Partial<PathPlan> = {}) {
        if (!("GameRelativePath" in $$source)) {
            this["GameRelativePath"] = "";
        }
        if (!("PlannedAction" in $$source)) {
            this["PlannedAction"] = ReapplyAction.$zero;
        }
        if (!("FileStatus" in $$source)) {
            this["FileStatus"] = deployment$0.FileStatus.$zero;
        }
        if (!("RiskLevel" in $$source)) {
            this["RiskLevel"] = deployment$0.RiskLevel.$zero;
        }
        if (!("ConflictCategory" in $$source)) {
            this["ConflictCategory"] = deployment$0.ConflictCategory.$zero;
        }
        if (!("DriftKind" in $$source)) {
            this["DriftKind"] = deployment$0.DriftKind.$zero;
        }
        if (!("Baseline" in $$source)) {
            this["Baseline"] = (new FileStateSnapshot());
        }
        if (!("Applied" in $$source)) {
            this["Applied"] = (new FileStateSnapshot());
        }
        if (!("Current" in $$source)) {
            this["Current"] = (new FileStateSnapshot());
        }
        if (!("Desired" in $$source)) {
            this["Desired"] = (new FileStateSnapshot());
        }
        if (!("BaselineBackupPath" in $$source)) {
            this["BaselineBackupPath"] = "";
        }
        if (!("LastAppliedAt" in $$source)) {
            this["LastAppliedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PathPlan instance from a string or object.
     */
    static createFrom($$source: any = {}): PathPlan {
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType4;
        const $$createField8_0 = $$createType4;
        const $$createField9_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Baseline" in $$parsedSource) {
            $$parsedSource["Baseline"] = $$createField6_0($$parsedSource["Baseline"]);
        }
        if ("Applied" in $$parsedSource) {
            $$parsedSource["Applied"] = $$createField7_0($$parsedSource["Applied"]);
        }
        if ("Current" in $$parsedSource) {
            $$parsedSource["Current"] = $$createField8_0($$parsedSource["Current"]);
        }
        if ("Desired" in $$parsedSource) {
            $$parsedSource["Desired"] = $$createField9_0($$parsedSource["Desired"]);
        }
        return new PathPlan($$parsedSource as Partial<PathPlan>);
    }
}

export enum PlanMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PlanModeFirstApply = "first_apply",
    PlanModeIncremental = "incremental",
};

export enum ReapplyAction {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ReapplyNoOp = "noop",
    ReapplyCreate = "create",
    ReapplyReplace = "replace",
    ReapplyDelete = "delete",
    ReapplyRestoreBaseline = "restore_baseline",
    ReapplyRepair = "repair",
    ReapplyRequireDecision = "require_decision",
    ReapplyBlock = "block",
};

// Private type creation functions
const $$createType0 = PathPlan.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = deployment$0.PlanIssue.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = FileStateSnapshot.createFrom;
