// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "./dto/models.js";

export function BuildDeploymentReviewPreview(profileID: number): $CancellablePromise<dto$0.DeploymentReviewPreview> {
    return $Call.ByID(1391596289, profileID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetDeploymentFileDetail(previewHash: string, relativePath: string): $CancellablePromise<dto$0.DeploymentFileDetail> {
    return $Call.ByID(3871491748, previewHash, relativePath).then(($result: any) => {
        return $$createType1($result);
    });
}

export function LoadDeploymentTreeChildren(previewHash: string, parentPath: string): $CancellablePromise<dto$0.DeploymentTreeNode[]> {
    return $Call.ByID(3992299200, previewHash, parentPath).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = dto$0.DeploymentReviewPreview.createFrom;
const $$createType1 = dto$0.DeploymentFileDetail.createFrom;
const $$createType2 = dto$0.DeploymentTreeNode.createFrom;
const $$createType3 = $Create.Array($$createType2);
