// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "./dto/models.js";

export function ClearDevLogs(): $CancellablePromise<void> {
    return $Call.ByID(2644314191);
}

export function GetDevInfo(): $CancellablePromise<dto$0.DevInfo> {
    return $Call.ByID(2405182247).then(($result: any) => {
        return $$createType0($result);
    });
}

export function IsDevMode(): $CancellablePromise<boolean> {
    return $Call.ByID(831126136);
}

export function ListDevLogs(limit: number): $CancellablePromise<dto$0.DevLogEntry[]> {
    return $Call.ByID(1790943252, limit).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = dto$0.DevInfo.createFrom;
const $$createType1 = dto$0.DevLogEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
