// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "./dto/models.js";

export function ExportLogs(input: dto$0.ExportDiagnosticLogsInput): $CancellablePromise<void> {
    return $Call.ByID(2191609694, input);
}

export function ListDiagnosticOperations(): $CancellablePromise<dto$0.DiagnosticOperationGroup[]> {
    return $Call.ByID(1831480386).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListRecentLogs(input: dto$0.ListDiagnosticLogsInput): $CancellablePromise<dto$0.DiagnosticLogEntry[]> {
    return $Call.ByID(1168352495, input).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListRecentRawLogs(input: dto$0.ListDiagnosticLogsInput): $CancellablePromise<string> {
    return $Call.ByID(4026490937, input);
}

// Private type creation functions
const $$createType0 = dto$0.DiagnosticOperationGroup.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = dto$0.DiagnosticLogEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
