// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "./dto/models.js";

export function GetStoredGames(): $CancellablePromise<dto$0.StoredGame[]> {
    return $Call.ByID(3698982394).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ScanAndSaveGames(): $CancellablePromise<dto$0.SourceScanResult> {
    return $Call.ByID(3535213326).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = dto$0.StoredGame.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = dto$0.SourceScanResult.createFrom;
