// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "./dto/models.js";

export function DeleteMod(modID: number): $CancellablePromise<void> {
    return $Call.ByID(2907973472, modID);
}

export function GetGameManagedModStorageUsage(gameID: number): $CancellablePromise<number> {
    return $Call.ByID(316010192, gameID);
}

export function GetModDeleteSummary(modID: number): $CancellablePromise<dto$0.ModDeleteSummary> {
    return $Call.ByID(794073036, modID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetModMetadata(modID: number): $CancellablePromise<dto$0.ModMetadata> {
    return $Call.ByID(3549730346, modID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ImportMod(input: dto$0.ImportModInput): $CancellablePromise<dto$0.ImportModResult> {
    return $Call.ByID(1549763346, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListImportStrategies(): $CancellablePromise<dto$0.StrategyDescriptor[]> {
    return $Call.ByID(2113312407).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListMods(gameID: number): $CancellablePromise<dto$0.Mod[]> {
    return $Call.ByID(3338520162, gameID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function PreValidateImport(input: dto$0.PreValidateImportInput): $CancellablePromise<void> {
    return $Call.ByID(3054738227, input);
}

export function PreviewImportConfiguration(input: dto$0.PreviewImportConfigurationInput): $CancellablePromise<dto$0.Preview> {
    return $Call.ByID(3729111778, input).then(($result: any) => {
        return $$createType7($result);
    });
}

export function RenameMod(modID: number, name: string): $CancellablePromise<dto$0.Mod> {
    return $Call.ByID(4073359283, modID, name).then(($result: any) => {
        return $$createType5($result);
    });
}

export function UpdateModMetadata(input: dto$0.UpdateModMetadataInput): $CancellablePromise<dto$0.ModMetadata> {
    return $Call.ByID(3991595271, input).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = dto$0.ModDeleteSummary.createFrom;
const $$createType1 = dto$0.ModMetadata.createFrom;
const $$createType2 = dto$0.ImportModResult.createFrom;
const $$createType3 = dto$0.StrategyDescriptor.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = dto$0.Mod.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = dto$0.Preview.createFrom;
