// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "./dto/models.js";

export function DeleteMod(modID: number): $CancellablePromise<void> {
    return $Call.ByID(2907973472, modID);
}

export function DetectImportTargets(gameID: number, strategyType: dto$0.StrategyType): $CancellablePromise<dto$0.ImportTargetDetectionResult> {
    return $Call.ByID(1498554145, gameID, strategyType).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetGameManagedModStorageUsage(gameID: number): $CancellablePromise<number> {
    return $Call.ByID(316010192, gameID);
}

export function GetModDeleteSummary(modID: number): $CancellablePromise<dto$0.ModDeleteSummary> {
    return $Call.ByID(794073036, modID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetModMetadata(modID: number): $CancellablePromise<dto$0.ModMetadata> {
    return $Call.ByID(3549730346, modID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ImportMod(input: dto$0.ImportModInput): $CancellablePromise<dto$0.ImportModResult> {
    return $Call.ByID(1549763346, input).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListGameTags(gameID: number): $CancellablePromise<dto$0.Tag[]> {
    return $Call.ByID(1728348392, gameID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ListImportStrategies(): $CancellablePromise<dto$0.StrategyDescriptor[]> {
    return $Call.ByID(2113312407).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListMods(gameID: number): $CancellablePromise<dto$0.Mod[]> {
    return $Call.ByID(3338520162, gameID).then(($result: any) => {
        return $$createType9($result);
    });
}

export function PreValidateImport(input: dto$0.PreValidateImportInput): $CancellablePromise<dto$0.PreValidateImportResult> {
    return $Call.ByID(3054738227, input).then(($result: any) => {
        return $$createType10($result);
    });
}

export function PreviewImportConfiguration(input: dto$0.PreviewImportConfigurationInput): $CancellablePromise<dto$0.Preview> {
    return $Call.ByID(3729111778, input).then(($result: any) => {
        return $$createType11($result);
    });
}

export function PreviewUpdateMod(input: dto$0.UpdateModInput): $CancellablePromise<dto$0.UpdateModResult> {
    return $Call.ByID(2400039676, input).then(($result: any) => {
        return $$createType12($result);
    });
}

export function RenameMod(modID: number, name: string): $CancellablePromise<dto$0.Mod> {
    return $Call.ByID(4073359283, modID, name).then(($result: any) => {
        return $$createType8($result);
    });
}

export function RenameTag(tagID: number, name: string, color: dto$0.TagColor): $CancellablePromise<dto$0.Tag> {
    return $Call.ByID(1280155363, tagID, name, color).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ResolveImportSourceDuplicates(input: dto$0.ResolveImportSourceDuplicatesInput): $CancellablePromise<dto$0.ResolveImportSourceDuplicatesResult> {
    return $Call.ByID(775457951, input).then(($result: any) => {
        return $$createType13($result);
    });
}

export function UpdateMod(input: dto$0.UpdateModInput): $CancellablePromise<dto$0.UpdateModResult> {
    return $Call.ByID(4122963090, input).then(($result: any) => {
        return $$createType12($result);
    });
}

export function UpdateModDetails(input: dto$0.UpdateModDetailsInput): $CancellablePromise<dto$0.Mod> {
    return $Call.ByID(3416247536, input).then(($result: any) => {
        return $$createType8($result);
    });
}

export function UpdateModMetadata(input: dto$0.UpdateModMetadataInput): $CancellablePromise<dto$0.ModMetadata> {
    return $Call.ByID(3991595271, input).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = dto$0.ImportTargetDetectionResult.createFrom;
const $$createType1 = dto$0.ModDeleteSummary.createFrom;
const $$createType2 = dto$0.ModMetadata.createFrom;
const $$createType3 = dto$0.ImportModResult.createFrom;
const $$createType4 = dto$0.Tag.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = dto$0.StrategyDescriptor.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = dto$0.Mod.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = dto$0.PreValidateImportResult.createFrom;
const $$createType11 = dto$0.Preview.createFrom;
const $$createType12 = dto$0.UpdateModResult.createFrom;
const $$createType13 = dto$0.ResolveImportSourceDuplicatesResult.createFrom;
