// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as optiscaler$0 from "../optiscaler/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "./dto/models.js";

export function ApplyOptiScalerAction(request: dto$0.OptiScalerRequest, previewHash: string): $CancellablePromise<dto$0.OptiScalerApplyResult> {
    return $Call.ByID(2777825503, request, previewHash).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ApplyOptiScalerReShadeRepair(previewHash: string): $CancellablePromise<dto$0.OptiScalerApplyResult> {
    return $Call.ByID(223216528, previewHash).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CancelOptiScalerReShadeSession(): $CancellablePromise<dto$0.OptiScalerReShadeSessionResult> {
    return $Call.ByID(1365315451).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DiscoverOptiScalerCandidates(gameID: number): $CancellablePromise<dto$0.OptiScalerCandidate[]> {
    return $Call.ByID(1051566546, gameID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetOptiScalerReShadeSession(): $CancellablePromise<dto$0.OptiScalerReShadeSessionState | null> {
    return $Call.ByID(3496975459).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetOptiScalerRecoveryState(): $CancellablePromise<dto$0.OptiScalerRecoveryState> {
    return $Call.ByID(3121407251).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetOptiScalerReleaseStatus(): $CancellablePromise<dto$0.OptiScalerRelease> {
    return $Call.ByID(1814290376).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListOptiScalerTargets(gameID: number): $CancellablePromise<dto$0.OptiScalerTarget[]> {
    return $Call.ByID(2329698055, gameID).then(($result: any) => {
        return $$createType9($result);
    });
}

export function PreviewOptiScalerAction(request: dto$0.OptiScalerRequest): $CancellablePromise<dto$0.OptiScalerPreview> {
    return $Call.ByID(2072722191, request).then(($result: any) => {
        return $$createType10($result);
    });
}

export function PreviewOptiScalerReShadeRepair(backupAndContinue: boolean): $CancellablePromise<dto$0.OptiScalerPreview> {
    return $Call.ByID(3942149152, backupAndContinue).then(($result: any) => {
        return $$createType10($result);
    });
}

export function RescanOptiScalerReShadeSession(): $CancellablePromise<dto$0.OptiScalerReShadeSessionResult> {
    return $Call.ByID(2070664681).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RollbackOptiScalerRecovery(journalID: string): $CancellablePromise<dto$0.OptiScalerApplyResult> {
    return $Call.ByID(1921712636, journalID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function StartOptiScalerReShadeSession(request: dto$0.OptiScalerReShadeSessionRequest): $CancellablePromise<dto$0.OptiScalerReShadeSessionState> {
    return $Call.ByID(3574130455, request).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = optiscaler$0.ApplyResult.createFrom;
const $$createType1 = optiscaler$0.ReShadeSessionResult.createFrom;
const $$createType2 = optiscaler$0.Candidate.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = optiscaler$0.ReShadeSessionState.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = optiscaler$0.RecoveryState.createFrom;
const $$createType7 = optiscaler$0.Release.createFrom;
const $$createType8 = dto$0.OptiScalerTarget.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = optiscaler$0.Preview.createFrom;
