// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as optiscaler$0 from "../optiscaler/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "./dto/models.js";

export function ApplyOptiScalerAction(request: dto$0.OptiScalerRequest, previewHash: string): $CancellablePromise<dto$0.OptiScalerApplyResult> {
    return $Call.ByID(2777825503, request, previewHash).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DiscoverOptiScalerCandidates(gameID: number): $CancellablePromise<dto$0.OptiScalerCandidate[]> {
    return $Call.ByID(1051566546, gameID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetOptiScalerRecoveryState(): $CancellablePromise<dto$0.OptiScalerRecoveryState> {
    return $Call.ByID(3121407251).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetOptiScalerReleaseStatus(refresh: boolean): $CancellablePromise<dto$0.OptiScalerRelease> {
    return $Call.ByID(1814290376, refresh).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListOptiScalerTargets(gameID: number): $CancellablePromise<dto$0.OptiScalerTarget[]> {
    return $Call.ByID(2329698055, gameID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function PreviewOptiScalerAction(request: dto$0.OptiScalerRequest): $CancellablePromise<dto$0.OptiScalerPreview> {
    return $Call.ByID(2072722191, request).then(($result: any) => {
        return $$createType7($result);
    });
}

export function RollbackOptiScalerRecovery(journalID: string): $CancellablePromise<dto$0.OptiScalerApplyResult> {
    return $Call.ByID(1921712636, journalID).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = optiscaler$0.ApplyResult.createFrom;
const $$createType1 = optiscaler$0.Candidate.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = optiscaler$0.RecoveryState.createFrom;
const $$createType4 = optiscaler$0.Release.createFrom;
const $$createType5 = dto$0.OptiScalerTarget.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = optiscaler$0.Preview.createFrom;
