// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appliedstate$0 from "../appliedstate/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as deployment$0 from "../deployment/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as execute$0 from "../deployment/execute/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as planner$0 from "../deployment/planner/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "./dto/models.js";

export function AddModToProfile(profileID: number, modID: number): $CancellablePromise<dto$0.ProfileMod> {
    return $Call.ByID(3187976695, profileID, modID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CreateProfile(gameID: number, name: string): $CancellablePromise<dto$0.ModProfile> {
    return $Call.ByID(3434881059, gameID, name).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteProfile(profileID: number): $CancellablePromise<void> {
    return $Call.ByID(1258387998, profileID);
}

export function DuplicateProfile(profileID: number): $CancellablePromise<dto$0.ModProfile> {
    return $Call.ByID(1945213396, profileID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetAppliedProfileSummary(gameID: number): $CancellablePromise<dto$0.AppliedProfileSummary | null> {
    return $Call.ByID(3862387448, gameID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListProfileMods(profileID: number): $CancellablePromise<dto$0.ProfileMod[]> {
    return $Call.ByID(2451536030, profileID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListProfiles(gameID: number): $CancellablePromise<dto$0.ModProfile[]> {
    return $Call.ByID(2077593160, gameID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function LoadAppliedFileStates(gameID: number): $CancellablePromise<appliedstate$0.PersistedFileState[]> {
    return $Call.ByID(2694248031, gameID).then(($result: any) => {
        return $$createType7($result);
    });
}

export function RemoveModFromProfile(profileID: number, modID: number): $CancellablePromise<void> {
    return $Call.ByID(3265852827, profileID, modID);
}

export function RenameProfile(profileID: number, name: string): $CancellablePromise<dto$0.ModProfile> {
    return $Call.ByID(4188934241, profileID, name).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ReorderProfileMods(profileID: number, modIDs: number[]): $CancellablePromise<dto$0.ProfileMod[]> {
    return $Call.ByID(879417303, profileID, modIDs).then(($result: any) => {
        return $$createType4($result);
    });
}

export function RestoreVanillaState(gameID: number): $CancellablePromise<dto$0.RestoreResult> {
    return $Call.ByID(1179292680, gameID).then(($result: any) => {
        return $$createType8($result);
    });
}

export function SaveFirstApplyAppliedProfileState(gameID: number, profileID: number, installPath: string, plan: planner$0.DeploymentPlan, desired: deployment$0.DesiredState, outcome: execute$0.FirstApplyOutcome, previewHash: string): $CancellablePromise<void> {
    return $Call.ByID(2383268840, gameID, profileID, installPath, plan, desired, outcome, previewHash);
}

export function SaveIncrementalAppliedProfileState(gameID: number, profileID: number, installPath: string, plan: planner$0.DeploymentPlan, desired: deployment$0.DesiredState, existingStates: appliedstate$0.PersistedFileState[]): $CancellablePromise<void> {
    return $Call.ByID(1318407708, gameID, profileID, installPath, plan, desired, existingStates);
}

export function SetProfileModEnabled(profileID: number, modID: number, enabled: boolean): $CancellablePromise<dto$0.ProfileMod> {
    return $Call.ByID(139934462, profileID, modID, enabled).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = dto$0.ProfileMod.createFrom;
const $$createType1 = dto$0.ModProfile.createFrom;
const $$createType2 = dto$0.AppliedProfileSummary.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = $Create.Array($$createType1);
const $$createType6 = appliedstate$0.PersistedFileState.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = dto$0.RestoreResult.createFrom;
