// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "./dto/models.js";

export function CheckForUpdates(): $CancellablePromise<void> {
    return $Call.ByID(2482572345);
}

export function CurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(2755764701);
}

export function EnsureGameModStoragePath(gameID: number): $CancellablePromise<string> {
    return $Call.ByID(2284468152, gameID);
}

export function GetGlobalModStorageRoot(): $CancellablePromise<string> {
    return $Call.ByID(502792444);
}

export function GetThemeID(): $CancellablePromise<string> {
    return $Call.ByID(3877864122);
}

export function ResolveGameModStoragePath(gameID: number): $CancellablePromise<string> {
    return $Call.ByID(3472233806, gameID);
}

export function SetGameModStoragePathOverride(gameID: number, path: string): $CancellablePromise<dto$0.StoredGame> {
    return $Call.ByID(1165004158, gameID, path).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetGlobalModStorageRoot(path: string): $CancellablePromise<void> {
    return $Call.ByID(4287125056, path);
}

export function SetThemeID(themeID: string): $CancellablePromise<void> {
    return $Call.ByID(2924940462, themeID);
}

// Private type creation functions
const $$createType0 = dto$0.StoredGame.createFrom;
