// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export enum Action {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ActionInstall = "install",
    ActionAdopt = "adopt",
    ActionUpdate = "update",
    ActionRepair = "repair",
    ActionUninstall = "uninstall",
    ActionReShadeRepair = "reshade_repair",
};

export class ApplyResult {
    "success": boolean;
    "rolledBack": boolean;
    "message": string;

    /** Creates a new ApplyResult instance. */
    constructor($$source: Partial<ApplyResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("rolledBack" in $$source)) {
            this["rolledBack"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplyResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ApplyResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApplyResult($$parsedSource as Partial<ApplyResult>);
    }
}

export class Candidate {
    "targetRelativePath": string;
    "executableRelativePath": string;
    "executableName": string;
    "architecture": string;
    "evidence": string[];
    "managed": boolean;
    "hasOptiScaler": boolean;
    "hasReShade": boolean;

    /** Creates a new Candidate instance. */
    constructor($$source: Partial<Candidate> = {}) {
        if (!("targetRelativePath" in $$source)) {
            this["targetRelativePath"] = "";
        }
        if (!("executableRelativePath" in $$source)) {
            this["executableRelativePath"] = "";
        }
        if (!("executableName" in $$source)) {
            this["executableName"] = "";
        }
        if (!("architecture" in $$source)) {
            this["architecture"] = "";
        }
        if (!("evidence" in $$source)) {
            this["evidence"] = [];
        }
        if (!("managed" in $$source)) {
            this["managed"] = false;
        }
        if (!("hasOptiScaler" in $$source)) {
            this["hasOptiScaler"] = false;
        }
        if (!("hasReShade" in $$source)) {
            this["hasReShade"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Candidate instance from a string or object.
     */
    static createFrom($$source: any = {}): Candidate {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("evidence" in $$parsedSource) {
            $$parsedSource["evidence"] = $$createField4_0($$parsedSource["evidence"]);
        }
        return new Candidate($$parsedSource as Partial<Candidate>);
    }
}

export class Drift {
    "relativePath": string;
    "expectedHash": string;
    "actualHash"?: string;
    "missing": boolean;

    /** Creates a new Drift instance. */
    constructor($$source: Partial<Drift> = {}) {
        if (!("relativePath" in $$source)) {
            this["relativePath"] = "";
        }
        if (!("expectedHash" in $$source)) {
            this["expectedHash"] = "";
        }
        if (!("missing" in $$source)) {
            this["missing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Drift instance from a string or object.
     */
    static createFrom($$source: any = {}): Drift {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Drift($$parsedSource as Partial<Drift>);
    }
}

export enum GraphicsAPI {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    GraphicsAPIDirectX = "directx",
    GraphicsAPIVulkan = "vulkan",
};

export class Operation {
    "type": string;
    "sourcePath"?: string;
    "targetPath": string;
    "backupPath"?: string;
    "sha256"?: string;
    "sizeBytes"?: number;

    /** Creates a new Operation instance. */
    constructor($$source: Partial<Operation> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("targetPath" in $$source)) {
            this["targetPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Operation instance from a string or object.
     */
    static createFrom($$source: any = {}): Operation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Operation($$parsedSource as Partial<Operation>);
    }
}

export class Preview {
    "request": Request;
    "release": Release;
    "operations": Operation[];
    "configurationChanges": string[];
    "warnings": string[];
    "conflicts": string[];
    "drift": Drift[];
    "previewHash": string;
    "canApply": boolean;

    /** Creates a new Preview instance. */
    constructor($$source: Partial<Preview> = {}) {
        if (!("request" in $$source)) {
            this["request"] = (new Request());
        }
        if (!("release" in $$source)) {
            this["release"] = (new Release());
        }
        if (!("operations" in $$source)) {
            this["operations"] = [];
        }
        if (!("configurationChanges" in $$source)) {
            this["configurationChanges"] = [];
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }
        if (!("conflicts" in $$source)) {
            this["conflicts"] = [];
        }
        if (!("drift" in $$source)) {
            this["drift"] = [];
        }
        if (!("previewHash" in $$source)) {
            this["previewHash"] = "";
        }
        if (!("canApply" in $$source)) {
            this["canApply"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preview instance from a string or object.
     */
    static createFrom($$source: any = {}): Preview {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("request" in $$parsedSource) {
            $$parsedSource["request"] = $$createField0_0($$parsedSource["request"]);
        }
        if ("release" in $$parsedSource) {
            $$parsedSource["release"] = $$createField1_0($$parsedSource["release"]);
        }
        if ("operations" in $$parsedSource) {
            $$parsedSource["operations"] = $$createField2_0($$parsedSource["operations"]);
        }
        if ("configurationChanges" in $$parsedSource) {
            $$parsedSource["configurationChanges"] = $$createField3_0($$parsedSource["configurationChanges"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField4_0($$parsedSource["warnings"]);
        }
        if ("conflicts" in $$parsedSource) {
            $$parsedSource["conflicts"] = $$createField5_0($$parsedSource["conflicts"]);
        }
        if ("drift" in $$parsedSource) {
            $$parsedSource["drift"] = $$createField6_0($$parsedSource["drift"]);
        }
        return new Preview($$parsedSource as Partial<Preview>);
    }
}

export enum ReShadeInstallerVariant {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ReShadeInstallerVariantStandard = "standard",
    ReShadeInstallerVariantAddon = "addon",
};

export enum ReShadeSessionOutcome {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ReShadeSessionOutcomeHealthy = "healthy",
    ReShadeSessionOutcomeRepairRequired = "repair_required",
    ReShadeSessionOutcomeConflict = "conflict",
    ReShadeSessionOutcomeCancelled = "cancelled",
};

export enum ReShadeSessionPhase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ReShadeSessionPhaseAwaitingCompletion = "awaiting_completion",
    ReShadeSessionPhaseRepairReady = "repair_ready",
    ReShadeSessionPhaseConflict = "conflict",
};

export class ReShadeSessionRequest {
    "gameId": number;
    "targetRelativePath": string;
    "installerVariant": ReShadeInstallerVariant;

    /** Creates a new ReShadeSessionRequest instance. */
    constructor($$source: Partial<ReShadeSessionRequest> = {}) {
        if (!("gameId" in $$source)) {
            this["gameId"] = 0;
        }
        if (!("targetRelativePath" in $$source)) {
            this["targetRelativePath"] = "";
        }
        if (!("installerVariant" in $$source)) {
            this["installerVariant"] = ReShadeInstallerVariant.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReShadeSessionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ReShadeSessionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReShadeSessionRequest($$parsedSource as Partial<ReShadeSessionRequest>);
    }
}

export class ReShadeSessionResult {
    "outcome": ReShadeSessionOutcome;
    "session"?: ReShadeSessionState | null;
    "message": string;

    /** Creates a new ReShadeSessionResult instance. */
    constructor($$source: Partial<ReShadeSessionResult> = {}) {
        if (!("outcome" in $$source)) {
            this["outcome"] = ReShadeSessionOutcome.$zero;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReShadeSessionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ReShadeSessionResult {
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField1_0($$parsedSource["session"]);
        }
        return new ReShadeSessionResult($$parsedSource as Partial<ReShadeSessionResult>);
    }
}

export class ReShadeSessionState {
    "id": string;
    "gameId": number;
    "targetRelativePath": string;
    "executableRelativePath": string;
    "proxyFilename": string;
    "chainedFilename": string;
    "installerVariant": ReShadeInstallerVariant;
    "phase": ReShadeSessionPhase;
    "startedAt": time$0.Time;
    "conflictingPath"?: string;
    "preview"?: Preview | null;

    /** Creates a new ReShadeSessionState instance. */
    constructor($$source: Partial<ReShadeSessionState> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("gameId" in $$source)) {
            this["gameId"] = 0;
        }
        if (!("targetRelativePath" in $$source)) {
            this["targetRelativePath"] = "";
        }
        if (!("executableRelativePath" in $$source)) {
            this["executableRelativePath"] = "";
        }
        if (!("proxyFilename" in $$source)) {
            this["proxyFilename"] = "";
        }
        if (!("chainedFilename" in $$source)) {
            this["chainedFilename"] = "";
        }
        if (!("installerVariant" in $$source)) {
            this["installerVariant"] = ReShadeInstallerVariant.$zero;
        }
        if (!("phase" in $$source)) {
            this["phase"] = ReShadeSessionPhase.$zero;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReShadeSessionState instance from a string or object.
     */
    static createFrom($$source: any = {}): ReShadeSessionState {
        const $$createField10_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("preview" in $$parsedSource) {
            $$parsedSource["preview"] = $$createField10_0($$parsedSource["preview"]);
        }
        return new ReShadeSessionState($$parsedSource as Partial<ReShadeSessionState>);
    }
}

export class RecoveryState {
    "required": boolean;
    "journalId"?: string;
    "gameId"?: number;
    "targetPath"?: string;
    "action"?: Action;
    "startedAt"?: time$0.Time;
    "error"?: string;

    /** Creates a new RecoveryState instance. */
    constructor($$source: Partial<RecoveryState> = {}) {
        if (!("required" in $$source)) {
            this["required"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecoveryState instance from a string or object.
     */
    static createFrom($$source: any = {}): RecoveryState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecoveryState($$parsedSource as Partial<RecoveryState>);
    }
}

export class Release {
    "tag": string;
    "version": string;
    "assetName": string;
    "url": string;
    "digest": string;
    "size": number;

    /** Creates a new Release instance. */
    constructor($$source: Partial<Release> = {}) {
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("assetName" in $$source)) {
            this["assetName"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("digest" in $$source)) {
            this["digest"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Release instance from a string or object.
     */
    static createFrom($$source: any = {}): Release {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Release($$parsedSource as Partial<Release>);
    }
}

export class Request {
    "action": Action;
    "gameId": number;
    "targetRelativePath": string;
    "executableRelativePath": string;
    "graphicsApi": GraphicsAPI;
    "proxyFilename": string;
    "dxgiSpoofing": boolean;
    "processFilter": string | null;
    "acknowledgeWarning": boolean;
    "backupAndContinue": boolean;
    "enableReShadeCoexistence": boolean;

    /** Creates a new Request instance. */
    constructor($$source: Partial<Request> = {}) {
        if (!("action" in $$source)) {
            this["action"] = Action.$zero;
        }
        if (!("gameId" in $$source)) {
            this["gameId"] = 0;
        }
        if (!("targetRelativePath" in $$source)) {
            this["targetRelativePath"] = "";
        }
        if (!("executableRelativePath" in $$source)) {
            this["executableRelativePath"] = "";
        }
        if (!("graphicsApi" in $$source)) {
            this["graphicsApi"] = GraphicsAPI.$zero;
        }
        if (!("proxyFilename" in $$source)) {
            this["proxyFilename"] = "";
        }
        if (!("dxgiSpoofing" in $$source)) {
            this["dxgiSpoofing"] = false;
        }
        if (!("processFilter" in $$source)) {
            this["processFilter"] = null;
        }
        if (!("acknowledgeWarning" in $$source)) {
            this["acknowledgeWarning"] = false;
        }
        if (!("backupAndContinue" in $$source)) {
            this["backupAndContinue"] = false;
        }
        if (!("enableReShadeCoexistence" in $$source)) {
            this["enableReShadeCoexistence"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Request instance from a string or object.
     */
    static createFrom($$source: any = {}): Request {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Request($$parsedSource as Partial<Request>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Request.createFrom;
const $$createType2 = Release.createFrom;
const $$createType3 = Operation.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = Drift.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = ReShadeSessionState.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = Preview.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
