// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BaselineBackup {
    "GameRelativePath": string;
    "BackupPath": string;
    "SHA256": string;
    "SizeBytes": number;

    /** Creates a new BaselineBackup instance. */
    constructor($$source: Partial<BaselineBackup> = {}) {
        if (!("GameRelativePath" in $$source)) {
            this["GameRelativePath"] = "";
        }
        if (!("BackupPath" in $$source)) {
            this["BackupPath"] = "";
        }
        if (!("SHA256" in $$source)) {
            this["SHA256"] = "";
        }
        if (!("SizeBytes" in $$source)) {
            this["SizeBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BaselineBackup instance from a string or object.
     */
    static createFrom($$source: any = {}): BaselineBackup {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BaselineBackup($$parsedSource as Partial<BaselineBackup>);
    }
}

export class CreatedDirectory {
    "TargetPath": string;
    "ModID": number;
    "ModName": string;

    /** Creates a new CreatedDirectory instance. */
    constructor($$source: Partial<CreatedDirectory> = {}) {
        if (!("TargetPath" in $$source)) {
            this["TargetPath"] = "";
        }
        if (!("ModID" in $$source)) {
            this["ModID"] = 0;
        }
        if (!("ModName" in $$source)) {
            this["ModName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreatedDirectory instance from a string or object.
     */
    static createFrom($$source: any = {}): CreatedDirectory {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreatedDirectory($$parsedSource as Partial<CreatedDirectory>);
    }
}

export class FirstApplyOutcome {
    "BaselineBackups": { [_ in string]?: BaselineBackup };
    "CreatedDirectories": CreatedDirectory[];

    /** Creates a new FirstApplyOutcome instance. */
    constructor($$source: Partial<FirstApplyOutcome> = {}) {
        if (!("BaselineBackups" in $$source)) {
            this["BaselineBackups"] = {};
        }
        if (!("CreatedDirectories" in $$source)) {
            this["CreatedDirectories"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FirstApplyOutcome instance from a string or object.
     */
    static createFrom($$source: any = {}): FirstApplyOutcome {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("BaselineBackups" in $$parsedSource) {
            $$parsedSource["BaselineBackups"] = $$createField0_0($$parsedSource["BaselineBackups"]);
        }
        if ("CreatedDirectories" in $$parsedSource) {
            $$parsedSource["CreatedDirectories"] = $$createField1_0($$parsedSource["CreatedDirectories"]);
        }
        return new FirstApplyOutcome($$parsedSource as Partial<FirstApplyOutcome>);
    }
}

// Private type creation functions
const $$createType0 = BaselineBackup.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = CreatedDirectory.createFrom;
const $$createType3 = $Create.Array($$createType2);
