// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as injection$0 from "../../injection/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as optiscaler$0 from "../../optiscaler/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as reshade$0 from "../../reshade/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

export class AppliedProfileSummary {
    "GameID": number;
    "ProfileID": number;
    "ProfileName": string;
    "AppliedAt": string;
    "HasAppliedProfileChanged": boolean | null;

    /** Creates a new AppliedProfileSummary instance. */
    constructor($$source: Partial<AppliedProfileSummary> = {}) {
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("ProfileID" in $$source)) {
            this["ProfileID"] = 0;
        }
        if (!("ProfileName" in $$source)) {
            this["ProfileName"] = "";
        }
        if (!("AppliedAt" in $$source)) {
            this["AppliedAt"] = "";
        }
        if (!("HasAppliedProfileChanged" in $$source)) {
            this["HasAppliedProfileChanged"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppliedProfileSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): AppliedProfileSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppliedProfileSummary($$parsedSource as Partial<AppliedProfileSummary>);
    }
}

export class ApplyDeploymentResult {
    "Success": boolean;
    "CompletedCount": number;
    "SkippedCount": number;
    "Message": string;
    "RolledBack": boolean;

    /** Creates a new ApplyDeploymentResult instance. */
    constructor($$source: Partial<ApplyDeploymentResult> = {}) {
        if (!("Success" in $$source)) {
            this["Success"] = false;
        }
        if (!("CompletedCount" in $$source)) {
            this["CompletedCount"] = 0;
        }
        if (!("SkippedCount" in $$source)) {
            this["SkippedCount"] = 0;
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }
        if (!("RolledBack" in $$source)) {
            this["RolledBack"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplyDeploymentResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ApplyDeploymentResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApplyDeploymentResult($$parsedSource as Partial<ApplyDeploymentResult>);
    }
}

export class ArchiveEntry {
    "Path": string;
    "SizeBytes": number;
    "IsDirectory": boolean;

    /** Creates a new ArchiveEntry instance. */
    constructor($$source: Partial<ArchiveEntry> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("SizeBytes" in $$source)) {
            this["SizeBytes"] = 0;
        }
        if (!("IsDirectory" in $$source)) {
            this["IsDirectory"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchiveEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchiveEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArchiveEntry($$parsedSource as Partial<ArchiveEntry>);
    }
}

export class CreateTagInput {
    "Name": string;
    "Color": TagColor;

    /** Creates a new CreateTagInput instance. */
    constructor($$source: Partial<CreateTagInput> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Color" in $$source)) {
            this["Color"] = TagColor.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateTagInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateTagInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateTagInput($$parsedSource as Partial<CreateTagInput>);
    }
}

export class DeploymentFileDetail {
    "RelativePath": string;
    "States": FourStateView;
    "WriterStack": WriterEntryDTO[];
    "ConflictCategory": string;
    "FileStatus": string;
    "PlannedAction": string;
    "RiskLevel": string;
    "Explanation": string;
    "BackupAvailable": boolean;
    "AvailableActions": string[];
    "ConflictAvailableActions": string[];
    "SavedConflictRuleModID": number | null;
    "SavedConflictRuleModName": string;
    "ProfileModsURL": string;
    "UserDecision": string;
    "UserDecisionLabel": string;
    "DriftKind": string;
    "DriftExplanation": string;
    "Comparison": StateComparison;
    "LastAppliedAt": time$0.Time | null;

    /** Creates a new DeploymentFileDetail instance. */
    constructor($$source: Partial<DeploymentFileDetail> = {}) {
        if (!("RelativePath" in $$source)) {
            this["RelativePath"] = "";
        }
        if (!("States" in $$source)) {
            this["States"] = (new FourStateView());
        }
        if (!("WriterStack" in $$source)) {
            this["WriterStack"] = [];
        }
        if (!("ConflictCategory" in $$source)) {
            this["ConflictCategory"] = "";
        }
        if (!("FileStatus" in $$source)) {
            this["FileStatus"] = "";
        }
        if (!("PlannedAction" in $$source)) {
            this["PlannedAction"] = "";
        }
        if (!("RiskLevel" in $$source)) {
            this["RiskLevel"] = "";
        }
        if (!("Explanation" in $$source)) {
            this["Explanation"] = "";
        }
        if (!("BackupAvailable" in $$source)) {
            this["BackupAvailable"] = false;
        }
        if (!("AvailableActions" in $$source)) {
            this["AvailableActions"] = [];
        }
        if (!("ConflictAvailableActions" in $$source)) {
            this["ConflictAvailableActions"] = [];
        }
        if (!("SavedConflictRuleModID" in $$source)) {
            this["SavedConflictRuleModID"] = null;
        }
        if (!("SavedConflictRuleModName" in $$source)) {
            this["SavedConflictRuleModName"] = "";
        }
        if (!("ProfileModsURL" in $$source)) {
            this["ProfileModsURL"] = "";
        }
        if (!("UserDecision" in $$source)) {
            this["UserDecision"] = "";
        }
        if (!("UserDecisionLabel" in $$source)) {
            this["UserDecisionLabel"] = "";
        }
        if (!("DriftKind" in $$source)) {
            this["DriftKind"] = "";
        }
        if (!("DriftExplanation" in $$source)) {
            this["DriftExplanation"] = "";
        }
        if (!("Comparison" in $$source)) {
            this["Comparison"] = (new StateComparison());
        }
        if (!("LastAppliedAt" in $$source)) {
            this["LastAppliedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeploymentFileDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): DeploymentFileDetail {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType2;
        const $$createField9_0 = $$createType3;
        const $$createField10_0 = $$createType3;
        const $$createField18_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("States" in $$parsedSource) {
            $$parsedSource["States"] = $$createField1_0($$parsedSource["States"]);
        }
        if ("WriterStack" in $$parsedSource) {
            $$parsedSource["WriterStack"] = $$createField2_0($$parsedSource["WriterStack"]);
        }
        if ("AvailableActions" in $$parsedSource) {
            $$parsedSource["AvailableActions"] = $$createField9_0($$parsedSource["AvailableActions"]);
        }
        if ("ConflictAvailableActions" in $$parsedSource) {
            $$parsedSource["ConflictAvailableActions"] = $$createField10_0($$parsedSource["ConflictAvailableActions"]);
        }
        if ("Comparison" in $$parsedSource) {
            $$parsedSource["Comparison"] = $$createField18_0($$parsedSource["Comparison"]);
        }
        return new DeploymentFileDetail($$parsedSource as Partial<DeploymentFileDetail>);
    }
}

export class DeploymentFileInspection {
    "RelativePath": string;
    "Kind": string;
    "LeftState": string;
    "RightState": string;
    "Left": InspectionSideMetadata;
    "Right": InspectionSideMetadata;
    "TextLines": TextDiffLine[];
    "PEMetadataLeft": PEMetadata | null;
    "PEMetadataRight": PEMetadata | null;
    "ImageMetadataLeft": ImageMetadata | null;
    "ImageMetadataRight": ImageMetadata | null;
    "ArchiveEntriesLeft": ArchiveEntry[];
    "ArchiveEntriesRight": ArchiveEntry[];
    "LimitReached": boolean;
    "LimitReason": string;
    "FallbackReason": string;

    /** Creates a new DeploymentFileInspection instance. */
    constructor($$source: Partial<DeploymentFileInspection> = {}) {
        if (!("RelativePath" in $$source)) {
            this["RelativePath"] = "";
        }
        if (!("Kind" in $$source)) {
            this["Kind"] = "";
        }
        if (!("LeftState" in $$source)) {
            this["LeftState"] = "";
        }
        if (!("RightState" in $$source)) {
            this["RightState"] = "";
        }
        if (!("Left" in $$source)) {
            this["Left"] = (new InspectionSideMetadata());
        }
        if (!("Right" in $$source)) {
            this["Right"] = (new InspectionSideMetadata());
        }
        if (!("TextLines" in $$source)) {
            this["TextLines"] = [];
        }
        if (!("PEMetadataLeft" in $$source)) {
            this["PEMetadataLeft"] = null;
        }
        if (!("PEMetadataRight" in $$source)) {
            this["PEMetadataRight"] = null;
        }
        if (!("ImageMetadataLeft" in $$source)) {
            this["ImageMetadataLeft"] = null;
        }
        if (!("ImageMetadataRight" in $$source)) {
            this["ImageMetadataRight"] = null;
        }
        if (!("ArchiveEntriesLeft" in $$source)) {
            this["ArchiveEntriesLeft"] = [];
        }
        if (!("ArchiveEntriesRight" in $$source)) {
            this["ArchiveEntriesRight"] = [];
        }
        if (!("LimitReached" in $$source)) {
            this["LimitReached"] = false;
        }
        if (!("LimitReason" in $$source)) {
            this["LimitReason"] = "";
        }
        if (!("FallbackReason" in $$source)) {
            this["FallbackReason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeploymentFileInspection instance from a string or object.
     */
    static createFrom($$source: any = {}): DeploymentFileInspection {
        const $$createField4_0 = $$createType5;
        const $$createField5_0 = $$createType5;
        const $$createField6_0 = $$createType7;
        const $$createField7_0 = $$createType9;
        const $$createField8_0 = $$createType9;
        const $$createField9_0 = $$createType11;
        const $$createField10_0 = $$createType11;
        const $$createField11_0 = $$createType13;
        const $$createField12_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Left" in $$parsedSource) {
            $$parsedSource["Left"] = $$createField4_0($$parsedSource["Left"]);
        }
        if ("Right" in $$parsedSource) {
            $$parsedSource["Right"] = $$createField5_0($$parsedSource["Right"]);
        }
        if ("TextLines" in $$parsedSource) {
            $$parsedSource["TextLines"] = $$createField6_0($$parsedSource["TextLines"]);
        }
        if ("PEMetadataLeft" in $$parsedSource) {
            $$parsedSource["PEMetadataLeft"] = $$createField7_0($$parsedSource["PEMetadataLeft"]);
        }
        if ("PEMetadataRight" in $$parsedSource) {
            $$parsedSource["PEMetadataRight"] = $$createField8_0($$parsedSource["PEMetadataRight"]);
        }
        if ("ImageMetadataLeft" in $$parsedSource) {
            $$parsedSource["ImageMetadataLeft"] = $$createField9_0($$parsedSource["ImageMetadataLeft"]);
        }
        if ("ImageMetadataRight" in $$parsedSource) {
            $$parsedSource["ImageMetadataRight"] = $$createField10_0($$parsedSource["ImageMetadataRight"]);
        }
        if ("ArchiveEntriesLeft" in $$parsedSource) {
            $$parsedSource["ArchiveEntriesLeft"] = $$createField11_0($$parsedSource["ArchiveEntriesLeft"]);
        }
        if ("ArchiveEntriesRight" in $$parsedSource) {
            $$parsedSource["ArchiveEntriesRight"] = $$createField12_0($$parsedSource["ArchiveEntriesRight"]);
        }
        return new DeploymentFileInspection($$parsedSource as Partial<DeploymentFileInspection>);
    }
}

export class DeploymentReviewPreview {
    "Summary": DeploymentSummary;
    "Root": DeploymentTreeNode;
    "PreviewHash": string;

    /** Creates a new DeploymentReviewPreview instance. */
    constructor($$source: Partial<DeploymentReviewPreview> = {}) {
        if (!("Summary" in $$source)) {
            this["Summary"] = (new DeploymentSummary());
        }
        if (!("Root" in $$source)) {
            this["Root"] = (new DeploymentTreeNode());
        }
        if (!("PreviewHash" in $$source)) {
            this["PreviewHash"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeploymentReviewPreview instance from a string or object.
     */
    static createFrom($$source: any = {}): DeploymentReviewPreview {
        const $$createField0_0 = $$createType14;
        const $$createField1_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Summary" in $$parsedSource) {
            $$parsedSource["Summary"] = $$createField0_0($$parsedSource["Summary"]);
        }
        if ("Root" in $$parsedSource) {
            $$parsedSource["Root"] = $$createField1_0($$parsedSource["Root"]);
        }
        return new DeploymentReviewPreview($$parsedSource as Partial<DeploymentReviewPreview>);
    }
}

export class DeploymentSummary {
    "GameID": number;
    "ProfileID": number;
    "ProfileName": string;
    "AppliedAt": time$0.Time | null;
    "PlanMode": string;
    "StatusCounts": { [_ in string]?: number };
    "CanApply": boolean;
    "PreviewHash": string;
    "BlockingCount": number;
    "WarningCount": number;
    "PreviousApplyAt": time$0.Time | null;

    /** Creates a new DeploymentSummary instance. */
    constructor($$source: Partial<DeploymentSummary> = {}) {
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("ProfileID" in $$source)) {
            this["ProfileID"] = 0;
        }
        if (!("ProfileName" in $$source)) {
            this["ProfileName"] = "";
        }
        if (!("AppliedAt" in $$source)) {
            this["AppliedAt"] = null;
        }
        if (!("PlanMode" in $$source)) {
            this["PlanMode"] = "";
        }
        if (!("StatusCounts" in $$source)) {
            this["StatusCounts"] = {};
        }
        if (!("CanApply" in $$source)) {
            this["CanApply"] = false;
        }
        if (!("PreviewHash" in $$source)) {
            this["PreviewHash"] = "";
        }
        if (!("BlockingCount" in $$source)) {
            this["BlockingCount"] = 0;
        }
        if (!("WarningCount" in $$source)) {
            this["WarningCount"] = 0;
        }
        if (!("PreviousApplyAt" in $$source)) {
            this["PreviousApplyAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeploymentSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): DeploymentSummary {
        const $$createField5_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("StatusCounts" in $$parsedSource) {
            $$parsedSource["StatusCounts"] = $$createField5_0($$parsedSource["StatusCounts"]);
        }
        return new DeploymentSummary($$parsedSource as Partial<DeploymentSummary>);
    }
}

export class DeploymentTreeNode {
    "Path": string;
    "Name": string;
    "IsDirectory": boolean;
    "Status": string;
    "PlannedAction": string;
    "RiskLevel": string;
    "ChildCount": number;
    "HasChildren": boolean;
    "Children": DeploymentTreeNode[];

    /** Creates a new DeploymentTreeNode instance. */
    constructor($$source: Partial<DeploymentTreeNode> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("IsDirectory" in $$source)) {
            this["IsDirectory"] = false;
        }
        if (!("Status" in $$source)) {
            this["Status"] = "";
        }
        if (!("PlannedAction" in $$source)) {
            this["PlannedAction"] = "";
        }
        if (!("RiskLevel" in $$source)) {
            this["RiskLevel"] = "";
        }
        if (!("ChildCount" in $$source)) {
            this["ChildCount"] = 0;
        }
        if (!("HasChildren" in $$source)) {
            this["HasChildren"] = false;
        }
        if (!("Children" in $$source)) {
            this["Children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeploymentTreeNode instance from a string or object.
     */
    static createFrom($$source: any = {}): DeploymentTreeNode {
        const $$createField8_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Children" in $$parsedSource) {
            $$parsedSource["Children"] = $$createField8_0($$parsedSource["Children"]);
        }
        return new DeploymentTreeNode($$parsedSource as Partial<DeploymentTreeNode>);
    }
}

export class DetectedReShadeTarget {
    "Path": string;
    "Executables": string[];
    "ManagementStatus": reshade$0.ManagementStatus;

    /** Creates a new DetectedReShadeTarget instance. */
    constructor($$source: Partial<DetectedReShadeTarget> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Executables" in $$source)) {
            this["Executables"] = [];
        }
        if (!("ManagementStatus" in $$source)) {
            this["ManagementStatus"] = reshade$0.ManagementStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetectedReShadeTarget instance from a string or object.
     */
    static createFrom($$source: any = {}): DetectedReShadeTarget {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Executables" in $$parsedSource) {
            $$parsedSource["Executables"] = $$createField1_0($$parsedSource["Executables"]);
        }
        return new DetectedReShadeTarget($$parsedSource as Partial<DetectedReShadeTarget>);
    }
}

export class DevInfo {
    "DataDir": string;
    "DatabasePath": string;

    /** Creates a new DevInfo instance. */
    constructor($$source: Partial<DevInfo> = {}) {
        if (!("DataDir" in $$source)) {
            this["DataDir"] = "";
        }
        if (!("DatabasePath" in $$source)) {
            this["DatabasePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DevInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DevInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DevInfo($$parsedSource as Partial<DevInfo>);
    }
}

export class DevLogEntry {
    "Timestamp": string;
    "Message": string;

    /** Creates a new DevLogEntry instance. */
    constructor($$source: Partial<DevLogEntry> = {}) {
        if (!("Timestamp" in $$source)) {
            this["Timestamp"] = "";
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DevLogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): DevLogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DevLogEntry($$parsedSource as Partial<DevLogEntry>);
    }
}

export class DiagnosticLogEntry {
    "Timestamp": string;
    "Level": string;
    "Operation": string;
    "Message": string;
    "Details": { [_ in string]?: string };

    /** Creates a new DiagnosticLogEntry instance. */
    constructor($$source: Partial<DiagnosticLogEntry> = {}) {
        if (!("Timestamp" in $$source)) {
            this["Timestamp"] = "";
        }
        if (!("Level" in $$source)) {
            this["Level"] = "";
        }
        if (!("Operation" in $$source)) {
            this["Operation"] = "";
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }
        if (!("Details" in $$source)) {
            this["Details"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticLogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): DiagnosticLogEntry {
        const $$createField4_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Details" in $$parsedSource) {
            $$parsedSource["Details"] = $$createField4_0($$parsedSource["Details"]);
        }
        return new DiagnosticLogEntry($$parsedSource as Partial<DiagnosticLogEntry>);
    }
}

export class DiagnosticOperation {
    "Value": string;
    "Label": string;

    /** Creates a new DiagnosticOperation instance. */
    constructor($$source: Partial<DiagnosticOperation> = {}) {
        if (!("Value" in $$source)) {
            this["Value"] = "";
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticOperation instance from a string or object.
     */
    static createFrom($$source: any = {}): DiagnosticOperation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiagnosticOperation($$parsedSource as Partial<DiagnosticOperation>);
    }
}

export class ExportDiagnosticLogsInput {
    "Path": string;
    "Entries": DiagnosticLogEntry[];

    /** Creates a new ExportDiagnosticLogsInput instance. */
    constructor($$source: Partial<ExportDiagnosticLogsInput> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Entries" in $$source)) {
            this["Entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportDiagnosticLogsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportDiagnosticLogsInput {
        const $$createField1_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Entries" in $$parsedSource) {
            $$parsedSource["Entries"] = $$createField1_0($$parsedSource["Entries"]);
        }
        return new ExportDiagnosticLogsInput($$parsedSource as Partial<ExportDiagnosticLogsInput>);
    }
}

export class FileStateView {
    "Exists": boolean;
    "SHA256": string;
    "SizeBytes": number;
    "Label": string;

    /** Creates a new FileStateView instance. */
    constructor($$source: Partial<FileStateView> = {}) {
        if (!("Exists" in $$source)) {
            this["Exists"] = false;
        }
        if (!("SHA256" in $$source)) {
            this["SHA256"] = "";
        }
        if (!("SizeBytes" in $$source)) {
            this["SizeBytes"] = 0;
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileStateView instance from a string or object.
     */
    static createFrom($$source: any = {}): FileStateView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileStateView($$parsedSource as Partial<FileStateView>);
    }
}

export class FourStateView {
    "Baseline": FileStateView | null;
    "Applied": FileStateView | null;
    "Current": FileStateView | null;
    "Desired": FileStateView | null;

    /** Creates a new FourStateView instance. */
    constructor($$source: Partial<FourStateView> = {}) {
        if (!("Baseline" in $$source)) {
            this["Baseline"] = null;
        }
        if (!("Applied" in $$source)) {
            this["Applied"] = null;
        }
        if (!("Current" in $$source)) {
            this["Current"] = null;
        }
        if (!("Desired" in $$source)) {
            this["Desired"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FourStateView instance from a string or object.
     */
    static createFrom($$source: any = {}): FourStateView {
        const $$createField0_0 = $$createType22;
        const $$createField1_0 = $$createType22;
        const $$createField2_0 = $$createType22;
        const $$createField3_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Baseline" in $$parsedSource) {
            $$parsedSource["Baseline"] = $$createField0_0($$parsedSource["Baseline"]);
        }
        if ("Applied" in $$parsedSource) {
            $$parsedSource["Applied"] = $$createField1_0($$parsedSource["Applied"]);
        }
        if ("Current" in $$parsedSource) {
            $$parsedSource["Current"] = $$createField2_0($$parsedSource["Current"]);
        }
        if ("Desired" in $$parsedSource) {
            $$parsedSource["Desired"] = $$createField3_0($$parsedSource["Desired"]);
        }
        return new FourStateView($$parsedSource as Partial<FourStateView>);
    }
}

export class ImageMetadata {
    "Format": string;
    "Width": number;
    "Height": number;
    "SHA256": string;
    "SizeBytes": number;

    /** Creates a new ImageMetadata instance. */
    constructor($$source: Partial<ImageMetadata> = {}) {
        if (!("Format" in $$source)) {
            this["Format"] = "";
        }
        if (!("Width" in $$source)) {
            this["Width"] = 0;
        }
        if (!("Height" in $$source)) {
            this["Height"] = 0;
        }
        if (!("SHA256" in $$source)) {
            this["SHA256"] = "";
        }
        if (!("SizeBytes" in $$source)) {
            this["SizeBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImageMetadata instance from a string or object.
     */
    static createFrom($$source: any = {}): ImageMetadata {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImageMetadata($$parsedSource as Partial<ImageMetadata>);
    }
}

export class ImportModInput {
    "GameID": number;
    "Name": string;
    "SourceType": ModSourceType;
    "SourcePath": string;
    "StrategyType": StrategyType;
    "TargetRelativePath": string;
    "TagIDs": number[];
    "NewTags": CreateTagInput[];

    /** Creates a new ImportModInput instance. */
    constructor($$source: Partial<ImportModInput> = {}) {
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("SourceType" in $$source)) {
            this["SourceType"] = ModSourceType.$zero;
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }
        if (!("StrategyType" in $$source)) {
            this["StrategyType"] = StrategyType.$zero;
        }
        if (!("TargetRelativePath" in $$source)) {
            this["TargetRelativePath"] = "";
        }
        if (!("TagIDs" in $$source)) {
            this["TagIDs"] = [];
        }
        if (!("NewTags" in $$source)) {
            this["NewTags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportModInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportModInput {
        const $$createField6_0 = $$createType23;
        const $$createField7_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("TagIDs" in $$parsedSource) {
            $$parsedSource["TagIDs"] = $$createField6_0($$parsedSource["TagIDs"]);
        }
        if ("NewTags" in $$parsedSource) {
            $$parsedSource["NewTags"] = $$createField7_0($$parsedSource["NewTags"]);
        }
        return new ImportModInput($$parsedSource as Partial<ImportModInput>);
    }
}

export class ImportModResult {
    "Mod": Mod;
    "Config": ModInstallConfig;
    "Warnings": string[];

    /** Creates a new ImportModResult instance. */
    constructor($$source: Partial<ImportModResult> = {}) {
        if (!("Mod" in $$source)) {
            this["Mod"] = (new Mod());
        }
        if (!("Config" in $$source)) {
            this["Config"] = (new ModInstallConfig());
        }
        if (!("Warnings" in $$source)) {
            this["Warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportModResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportModResult {
        const $$createField0_0 = $$createType26;
        const $$createField1_0 = $$createType27;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mod" in $$parsedSource) {
            $$parsedSource["Mod"] = $$createField0_0($$parsedSource["Mod"]);
        }
        if ("Config" in $$parsedSource) {
            $$parsedSource["Config"] = $$createField1_0($$parsedSource["Config"]);
        }
        if ("Warnings" in $$parsedSource) {
            $$parsedSource["Warnings"] = $$createField2_0($$parsedSource["Warnings"]);
        }
        return new ImportModResult($$parsedSource as Partial<ImportModResult>);
    }
}

export class ImportSourceDuplicateStatus {
    "SourceType": ModSourceType;
    "SourcePath": string;
    "CanonicalPath": string;
    "Error": string | null;
    "IsDuplicate": boolean;
    "ExistingModID": number | null;
    "ExistingModName": string | null;

    /** Creates a new ImportSourceDuplicateStatus instance. */
    constructor($$source: Partial<ImportSourceDuplicateStatus> = {}) {
        if (!("SourceType" in $$source)) {
            this["SourceType"] = ModSourceType.$zero;
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }
        if (!("CanonicalPath" in $$source)) {
            this["CanonicalPath"] = "";
        }
        if (!("Error" in $$source)) {
            this["Error"] = null;
        }
        if (!("IsDuplicate" in $$source)) {
            this["IsDuplicate"] = false;
        }
        if (!("ExistingModID" in $$source)) {
            this["ExistingModID"] = null;
        }
        if (!("ExistingModName" in $$source)) {
            this["ExistingModName"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportSourceDuplicateStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportSourceDuplicateStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportSourceDuplicateStatus($$parsedSource as Partial<ImportSourceDuplicateStatus>);
    }
}

export class ImportSourceRef {
    "SourceType": ModSourceType;
    "SourcePath": string;

    /** Creates a new ImportSourceRef instance. */
    constructor($$source: Partial<ImportSourceRef> = {}) {
        if (!("SourceType" in $$source)) {
            this["SourceType"] = ModSourceType.$zero;
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportSourceRef instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportSourceRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportSourceRef($$parsedSource as Partial<ImportSourceRef>);
    }
}

export class ImportTargetDetectionResult {
    "Candidates": string[];
    "Warnings": string[];

    /** Creates a new ImportTargetDetectionResult instance. */
    constructor($$source: Partial<ImportTargetDetectionResult> = {}) {
        if (!("Candidates" in $$source)) {
            this["Candidates"] = [];
        }
        if (!("Warnings" in $$source)) {
            this["Warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportTargetDetectionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportTargetDetectionResult {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Candidates" in $$parsedSource) {
            $$parsedSource["Candidates"] = $$createField0_0($$parsedSource["Candidates"]);
        }
        if ("Warnings" in $$parsedSource) {
            $$parsedSource["Warnings"] = $$createField1_0($$parsedSource["Warnings"]);
        }
        return new ImportTargetDetectionResult($$parsedSource as Partial<ImportTargetDetectionResult>);
    }
}

export class InspectionSideMetadata {
    "StateKind": string;
    "Label": string;
    "Available": boolean;
    "UnavailableReason": string;
    "SHA256": string;
    "SizeBytes": number;

    /** Creates a new InspectionSideMetadata instance. */
    constructor($$source: Partial<InspectionSideMetadata> = {}) {
        if (!("StateKind" in $$source)) {
            this["StateKind"] = "";
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Available" in $$source)) {
            this["Available"] = false;
        }
        if (!("UnavailableReason" in $$source)) {
            this["UnavailableReason"] = "";
        }
        if (!("SHA256" in $$source)) {
            this["SHA256"] = "";
        }
        if (!("SizeBytes" in $$source)) {
            this["SizeBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InspectionSideMetadata instance from a string or object.
     */
    static createFrom($$source: any = {}): InspectionSideMetadata {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InspectionSideMetadata($$parsedSource as Partial<InspectionSideMetadata>);
    }
}

export class ListDiagnosticLogsInput {
    "Limit": number;
    "Operation": string;
    "Level": string;

    /** Creates a new ListDiagnosticLogsInput instance. */
    constructor($$source: Partial<ListDiagnosticLogsInput> = {}) {
        if (!("Limit" in $$source)) {
            this["Limit"] = 0;
        }
        if (!("Operation" in $$source)) {
            this["Operation"] = "";
        }
        if (!("Level" in $$source)) {
            this["Level"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListDiagnosticLogsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ListDiagnosticLogsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListDiagnosticLogsInput($$parsedSource as Partial<ListDiagnosticLogsInput>);
    }
}

export class Mod {
    "ID": number;
    "GameID": number;
    "Name": string;
    "SourceType": ModSourceType;
    "SourcePath": string;
    "OriginalSourcePath": string;
    "OriginalSourceName": string | null;
    "FileCount": number | null;
    "DirectoryCount": number | null;
    "TotalSizeBytes": number | null;
    "MetadataJSON": string | null;
    "Metadata": ModMetadata | null;
    "CreatedAt": string;
    "UpdatedAt": string;
    "Tags": Tag[];

    /** Creates a new Mod instance. */
    constructor($$source: Partial<Mod> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("SourceType" in $$source)) {
            this["SourceType"] = ModSourceType.$zero;
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }
        if (!("OriginalSourcePath" in $$source)) {
            this["OriginalSourcePath"] = "";
        }
        if (!("OriginalSourceName" in $$source)) {
            this["OriginalSourceName"] = null;
        }
        if (!("FileCount" in $$source)) {
            this["FileCount"] = null;
        }
        if (!("DirectoryCount" in $$source)) {
            this["DirectoryCount"] = null;
        }
        if (!("TotalSizeBytes" in $$source)) {
            this["TotalSizeBytes"] = null;
        }
        if (!("MetadataJSON" in $$source)) {
            this["MetadataJSON"] = null;
        }
        if (!("Metadata" in $$source)) {
            this["Metadata"] = null;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = "";
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = "";
        }
        if (!("Tags" in $$source)) {
            this["Tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Mod instance from a string or object.
     */
    static createFrom($$source: any = {}): Mod {
        const $$createField11_0 = $$createType29;
        const $$createField14_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Metadata" in $$parsedSource) {
            $$parsedSource["Metadata"] = $$createField11_0($$parsedSource["Metadata"]);
        }
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField14_0($$parsedSource["Tags"]);
        }
        return new Mod($$parsedSource as Partial<Mod>);
    }
}

export class ModDeleteSummary {
    "ModID": number;
    "ModName": string;
    "ProfileUsageCount": number;
    "IsInAppliedProfile": boolean;
    "ManagedSourcePath": string;
    "OriginalSourceName": string | null;
    "OriginalSourcePath": string;

    /** Creates a new ModDeleteSummary instance. */
    constructor($$source: Partial<ModDeleteSummary> = {}) {
        if (!("ModID" in $$source)) {
            this["ModID"] = 0;
        }
        if (!("ModName" in $$source)) {
            this["ModName"] = "";
        }
        if (!("ProfileUsageCount" in $$source)) {
            this["ProfileUsageCount"] = 0;
        }
        if (!("IsInAppliedProfile" in $$source)) {
            this["IsInAppliedProfile"] = false;
        }
        if (!("ManagedSourcePath" in $$source)) {
            this["ManagedSourcePath"] = "";
        }
        if (!("OriginalSourceName" in $$source)) {
            this["OriginalSourceName"] = null;
        }
        if (!("OriginalSourcePath" in $$source)) {
            this["OriginalSourcePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModDeleteSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ModDeleteSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModDeleteSummary($$parsedSource as Partial<ModDeleteSummary>);
    }
}

export class ModDetectedMetadataSnapshot {
    "Version": string | null;
    "Author": string | null;
    "Description": string | null;
    "SourceURL": string | null;

    /** Creates a new ModDetectedMetadataSnapshot instance. */
    constructor($$source: Partial<ModDetectedMetadataSnapshot> = {}) {
        if (!("Version" in $$source)) {
            this["Version"] = null;
        }
        if (!("Author" in $$source)) {
            this["Author"] = null;
        }
        if (!("Description" in $$source)) {
            this["Description"] = null;
        }
        if (!("SourceURL" in $$source)) {
            this["SourceURL"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModDetectedMetadataSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): ModDetectedMetadataSnapshot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModDetectedMetadataSnapshot($$parsedSource as Partial<ModDetectedMetadataSnapshot>);
    }
}

export class ModInstallConfig {
    "ModID": number;
    "StrategyType": string;
    "TargetBase": string;
    "TargetRelativePath": string;
    "SourceSubpath": string | null;
    "CreatedAt": string;
    "UpdatedAt": string;

    /** Creates a new ModInstallConfig instance. */
    constructor($$source: Partial<ModInstallConfig> = {}) {
        if (!("ModID" in $$source)) {
            this["ModID"] = 0;
        }
        if (!("StrategyType" in $$source)) {
            this["StrategyType"] = "";
        }
        if (!("TargetBase" in $$source)) {
            this["TargetBase"] = "";
        }
        if (!("TargetRelativePath" in $$source)) {
            this["TargetRelativePath"] = "";
        }
        if (!("SourceSubpath" in $$source)) {
            this["SourceSubpath"] = null;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = "";
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModInstallConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ModInstallConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModInstallConfig($$parsedSource as Partial<ModInstallConfig>);
    }
}

export class ModMetadata {
    "ModID": number;
    "Version": ModMetadataField;
    "Author": ModMetadataField;
    "Description": ModMetadataField;
    "SourceURL": ModMetadataField;
    "Notes": string | null;
    "CreatedAt": string;
    "UpdatedAt": string;

    /** Creates a new ModMetadata instance. */
    constructor($$source: Partial<ModMetadata> = {}) {
        if (!("ModID" in $$source)) {
            this["ModID"] = 0;
        }
        if (!("Version" in $$source)) {
            this["Version"] = (new ModMetadataField());
        }
        if (!("Author" in $$source)) {
            this["Author"] = (new ModMetadataField());
        }
        if (!("Description" in $$source)) {
            this["Description"] = (new ModMetadataField());
        }
        if (!("SourceURL" in $$source)) {
            this["SourceURL"] = (new ModMetadataField());
        }
        if (!("Notes" in $$source)) {
            this["Notes"] = null;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = "";
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModMetadata instance from a string or object.
     */
    static createFrom($$source: any = {}): ModMetadata {
        const $$createField1_0 = $$createType32;
        const $$createField2_0 = $$createType32;
        const $$createField3_0 = $$createType32;
        const $$createField4_0 = $$createType32;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Version" in $$parsedSource) {
            $$parsedSource["Version"] = $$createField1_0($$parsedSource["Version"]);
        }
        if ("Author" in $$parsedSource) {
            $$parsedSource["Author"] = $$createField2_0($$parsedSource["Author"]);
        }
        if ("Description" in $$parsedSource) {
            $$parsedSource["Description"] = $$createField3_0($$parsedSource["Description"]);
        }
        if ("SourceURL" in $$parsedSource) {
            $$parsedSource["SourceURL"] = $$createField4_0($$parsedSource["SourceURL"]);
        }
        return new ModMetadata($$parsedSource as Partial<ModMetadata>);
    }
}

export class ModMetadataField {
    "Detected": string | null;
    "User": string | null;
    "UserSet": boolean;
    "Effective": string | null;

    /** Creates a new ModMetadataField instance. */
    constructor($$source: Partial<ModMetadataField> = {}) {
        if (!("Detected" in $$source)) {
            this["Detected"] = null;
        }
        if (!("User" in $$source)) {
            this["User"] = null;
        }
        if (!("UserSet" in $$source)) {
            this["UserSet"] = false;
        }
        if (!("Effective" in $$source)) {
            this["Effective"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModMetadataField instance from a string or object.
     */
    static createFrom($$source: any = {}): ModMetadataField {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModMetadataField($$parsedSource as Partial<ModMetadataField>);
    }
}

export class ModMetadataFieldUpdate {
    "Mode": ModMetadataFieldUpdateMode;
    "Value": string | null;

    /** Creates a new ModMetadataFieldUpdate instance. */
    constructor($$source: Partial<ModMetadataFieldUpdate> = {}) {
        if (!("Mode" in $$source)) {
            this["Mode"] = ModMetadataFieldUpdateMode.$zero;
        }
        if (!("Value" in $$source)) {
            this["Value"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModMetadataFieldUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): ModMetadataFieldUpdate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModMetadataFieldUpdate($$parsedSource as Partial<ModMetadataFieldUpdate>);
    }
}

export enum ModMetadataFieldUpdateMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ModMetadataFieldUpdateModeUser = "user",
    ModMetadataFieldUpdateModeClear = "clear",
    ModMetadataFieldUpdateModeReset = "reset",
};

export class ModPackageSnapshot {
    "SourceType": ModSourceType;
    "OriginalSourcePath": string;
    "OriginalSourceName": string | null;
    "FileCount": number | null;
    "DirectoryCount": number | null;
    "TotalSizeBytes": number | null;
    "DetectedMetadata": ModDetectedMetadataSnapshot;

    /** Creates a new ModPackageSnapshot instance. */
    constructor($$source: Partial<ModPackageSnapshot> = {}) {
        if (!("SourceType" in $$source)) {
            this["SourceType"] = ModSourceType.$zero;
        }
        if (!("OriginalSourcePath" in $$source)) {
            this["OriginalSourcePath"] = "";
        }
        if (!("OriginalSourceName" in $$source)) {
            this["OriginalSourceName"] = null;
        }
        if (!("FileCount" in $$source)) {
            this["FileCount"] = null;
        }
        if (!("DirectoryCount" in $$source)) {
            this["DirectoryCount"] = null;
        }
        if (!("TotalSizeBytes" in $$source)) {
            this["TotalSizeBytes"] = null;
        }
        if (!("DetectedMetadata" in $$source)) {
            this["DetectedMetadata"] = (new ModDetectedMetadataSnapshot());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModPackageSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): ModPackageSnapshot {
        const $$createField6_0 = $$createType33;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("DetectedMetadata" in $$parsedSource) {
            $$parsedSource["DetectedMetadata"] = $$createField6_0($$parsedSource["DetectedMetadata"]);
        }
        return new ModPackageSnapshot($$parsedSource as Partial<ModPackageSnapshot>);
    }
}

export class ModProfile {
    "ID": number;
    "GameID": number;
    "Name": string;
    "CreatedAt": string;
    "UpdatedAt": string;

    /** Creates a new ModProfile instance. */
    constructor($$source: Partial<ModProfile> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = "";
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): ModProfile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModProfile($$parsedSource as Partial<ModProfile>);
    }
}

export enum ModSourceType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ModSourceTypeFolder = "folder",
    ModSourceTypeArchive = "archive",
};

export const OptiScalerApplyResult = optiscaler$0.ApplyResult;
export type OptiScalerApplyResult = optiscaler$0.ApplyResult;

export const OptiScalerCandidate = optiscaler$0.Candidate;
export type OptiScalerCandidate = optiscaler$0.Candidate;

export const OptiScalerPreview = optiscaler$0.Preview;
export type OptiScalerPreview = optiscaler$0.Preview;

export const OptiScalerRecoveryState = optiscaler$0.RecoveryState;
export type OptiScalerRecoveryState = optiscaler$0.RecoveryState;

export const OptiScalerRelease = optiscaler$0.Release;
export type OptiScalerRelease = optiscaler$0.Release;

export const OptiScalerRequest = optiscaler$0.Request;
export type OptiScalerRequest = optiscaler$0.Request;

export class OptiScalerTarget {
    "ID": number;
    "GameID": number;
    "TargetRelativePath": string;
    "ExecutableRelativePath": string;
    "GraphicsAPI": string;
    "ProxyFilename": string;
    "DXGISpoofing": boolean;
    "ProcessFilter": string | null;
    "EnableReShadeCoexistence": boolean;
    "ReleaseTag": string;
    "ReleaseVersion": string;
    "ReleaseAssetName": string;
    "ReleaseDigest": string;
    "ManagementOrigin": string;
    "Status": string;
    "WarningVersion": string;
    "WarningAcknowledgedAt": string | null;
    "CreatedAt": string;
    "UpdatedAt": string;
    "LastVerifiedAt": string | null;

    /** Creates a new OptiScalerTarget instance. */
    constructor($$source: Partial<OptiScalerTarget> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("TargetRelativePath" in $$source)) {
            this["TargetRelativePath"] = "";
        }
        if (!("ExecutableRelativePath" in $$source)) {
            this["ExecutableRelativePath"] = "";
        }
        if (!("GraphicsAPI" in $$source)) {
            this["GraphicsAPI"] = "";
        }
        if (!("ProxyFilename" in $$source)) {
            this["ProxyFilename"] = "";
        }
        if (!("DXGISpoofing" in $$source)) {
            this["DXGISpoofing"] = false;
        }
        if (!("ProcessFilter" in $$source)) {
            this["ProcessFilter"] = null;
        }
        if (!("EnableReShadeCoexistence" in $$source)) {
            this["EnableReShadeCoexistence"] = false;
        }
        if (!("ReleaseTag" in $$source)) {
            this["ReleaseTag"] = "";
        }
        if (!("ReleaseVersion" in $$source)) {
            this["ReleaseVersion"] = "";
        }
        if (!("ReleaseAssetName" in $$source)) {
            this["ReleaseAssetName"] = "";
        }
        if (!("ReleaseDigest" in $$source)) {
            this["ReleaseDigest"] = "";
        }
        if (!("ManagementOrigin" in $$source)) {
            this["ManagementOrigin"] = "";
        }
        if (!("Status" in $$source)) {
            this["Status"] = "";
        }
        if (!("WarningVersion" in $$source)) {
            this["WarningVersion"] = "";
        }
        if (!("WarningAcknowledgedAt" in $$source)) {
            this["WarningAcknowledgedAt"] = null;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = "";
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = "";
        }
        if (!("LastVerifiedAt" in $$source)) {
            this["LastVerifiedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OptiScalerTarget instance from a string or object.
     */
    static createFrom($$source: any = {}): OptiScalerTarget {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OptiScalerTarget($$parsedSource as Partial<OptiScalerTarget>);
    }
}

export class PEMetadata {
    "Machine": string;
    "SectionCount": number;
    "Characteristics": string;
    "IsDLL": boolean;
    "IsEXE": boolean;
    "SHA256": string;
    "SizeBytes": number;

    /** Creates a new PEMetadata instance. */
    constructor($$source: Partial<PEMetadata> = {}) {
        if (!("Machine" in $$source)) {
            this["Machine"] = "";
        }
        if (!("SectionCount" in $$source)) {
            this["SectionCount"] = 0;
        }
        if (!("Characteristics" in $$source)) {
            this["Characteristics"] = "";
        }
        if (!("IsDLL" in $$source)) {
            this["IsDLL"] = false;
        }
        if (!("IsEXE" in $$source)) {
            this["IsEXE"] = false;
        }
        if (!("SHA256" in $$source)) {
            this["SHA256"] = "";
        }
        if (!("SizeBytes" in $$source)) {
            this["SizeBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PEMetadata instance from a string or object.
     */
    static createFrom($$source: any = {}): PEMetadata {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PEMetadata($$parsedSource as Partial<PEMetadata>);
    }
}

export class PreValidateImportInput {
    "SourceType": ModSourceType;
    "SourcePath": string;

    /** Creates a new PreValidateImportInput instance. */
    constructor($$source: Partial<PreValidateImportInput> = {}) {
        if (!("SourceType" in $$source)) {
            this["SourceType"] = ModSourceType.$zero;
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreValidateImportInput instance from a string or object.
     */
    static createFrom($$source: any = {}): PreValidateImportInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PreValidateImportInput($$parsedSource as Partial<PreValidateImportInput>);
    }
}

export class PreValidateImportResult {
    "SuggestedStrategy": StrategyType | null;

    /** Creates a new PreValidateImportResult instance. */
    constructor($$source: Partial<PreValidateImportResult> = {}) {
        if (!("SuggestedStrategy" in $$source)) {
            this["SuggestedStrategy"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreValidateImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PreValidateImportResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PreValidateImportResult($$parsedSource as Partial<PreValidateImportResult>);
    }
}

export class Preview {
    "StrategyType": StrategyType;
    "TargetBase": string;
    "TargetRelativePath": string;
    "TargetDisplayPath": string;
    "TotalFileCount": number;
    "TotalDirectoryCount": number;
    "TotalSizeBytes": number;
    "TargetFilePaths": string[];
    "IsCapped": boolean;
    "Cap": number;
    "Warnings": string[];

    /** Creates a new Preview instance. */
    constructor($$source: Partial<Preview> = {}) {
        if (!("StrategyType" in $$source)) {
            this["StrategyType"] = StrategyType.$zero;
        }
        if (!("TargetBase" in $$source)) {
            this["TargetBase"] = "";
        }
        if (!("TargetRelativePath" in $$source)) {
            this["TargetRelativePath"] = "";
        }
        if (!("TargetDisplayPath" in $$source)) {
            this["TargetDisplayPath"] = "";
        }
        if (!("TotalFileCount" in $$source)) {
            this["TotalFileCount"] = 0;
        }
        if (!("TotalDirectoryCount" in $$source)) {
            this["TotalDirectoryCount"] = 0;
        }
        if (!("TotalSizeBytes" in $$source)) {
            this["TotalSizeBytes"] = 0;
        }
        if (!("TargetFilePaths" in $$source)) {
            this["TargetFilePaths"] = [];
        }
        if (!("IsCapped" in $$source)) {
            this["IsCapped"] = false;
        }
        if (!("Cap" in $$source)) {
            this["Cap"] = 0;
        }
        if (!("Warnings" in $$source)) {
            this["Warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preview instance from a string or object.
     */
    static createFrom($$source: any = {}): Preview {
        const $$createField7_0 = $$createType3;
        const $$createField10_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("TargetFilePaths" in $$parsedSource) {
            $$parsedSource["TargetFilePaths"] = $$createField7_0($$parsedSource["TargetFilePaths"]);
        }
        if ("Warnings" in $$parsedSource) {
            $$parsedSource["Warnings"] = $$createField10_0($$parsedSource["Warnings"]);
        }
        return new Preview($$parsedSource as Partial<Preview>);
    }
}

export class PreviewImportConfigurationInput {
    "GameID": number;
    "SourceType": ModSourceType;
    "SourcePath": string;
    "StrategyType": StrategyType;
    "TargetRelativePath": string;

    /** Creates a new PreviewImportConfigurationInput instance. */
    constructor($$source: Partial<PreviewImportConfigurationInput> = {}) {
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("SourceType" in $$source)) {
            this["SourceType"] = ModSourceType.$zero;
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }
        if (!("StrategyType" in $$source)) {
            this["StrategyType"] = StrategyType.$zero;
        }
        if (!("TargetRelativePath" in $$source)) {
            this["TargetRelativePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewImportConfigurationInput instance from a string or object.
     */
    static createFrom($$source: any = {}): PreviewImportConfigurationInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PreviewImportConfigurationInput($$parsedSource as Partial<PreviewImportConfigurationInput>);
    }
}

export class ProfileMod {
    "ProfileID": number;
    "ModID": number;
    "Name": string;
    "SourcePath": string;
    "ModUpdatedAt": string;
    "Enabled": boolean;
    "LoadOrder": number;
    "DisplayLoadOrder": number;
    "CreatedAt": string;
    "UpdatedAt": string;

    /** Creates a new ProfileMod instance. */
    constructor($$source: Partial<ProfileMod> = {}) {
        if (!("ProfileID" in $$source)) {
            this["ProfileID"] = 0;
        }
        if (!("ModID" in $$source)) {
            this["ModID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }
        if (!("ModUpdatedAt" in $$source)) {
            this["ModUpdatedAt"] = "";
        }
        if (!("Enabled" in $$source)) {
            this["Enabled"] = false;
        }
        if (!("LoadOrder" in $$source)) {
            this["LoadOrder"] = 0;
        }
        if (!("DisplayLoadOrder" in $$source)) {
            this["DisplayLoadOrder"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = "";
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileMod instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileMod {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileMod($$parsedSource as Partial<ProfileMod>);
    }
}

export const ReShadeApplyResult = reshade$0.ApplyResult;
export type ReShadeApplyResult = reshade$0.ApplyResult;

export class ReShadeChainState {
    "PreferredProxyFilename": string;
    "ActiveRuntimeFilename": string;
    "Status": string;

    /** Creates a new ReShadeChainState instance. */
    constructor($$source: Partial<ReShadeChainState> = {}) {
        if (!("PreferredProxyFilename" in $$source)) {
            this["PreferredProxyFilename"] = "";
        }
        if (!("ActiveRuntimeFilename" in $$source)) {
            this["ActiveRuntimeFilename"] = "";
        }
        if (!("Status" in $$source)) {
            this["Status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReShadeChainState instance from a string or object.
     */
    static createFrom($$source: any = {}): ReShadeChainState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReShadeChainState($$parsedSource as Partial<ReShadeChainState>);
    }
}

export class ReShadeChainTarget {
    "GameID": number;
    "TargetRelativePath": string;
    "ExecutableRelativePath": string;
    "APIFamily": injection$0.APIFamily;
    "PrimaryOwner": injection$0.Owner;
    "PrimaryProxyFilename": string;
    "Status": injection$0.Status;
    "OptiScaler": ReShadeOptiScalerChainState | null;
    "ReShade": ReShadeChainState | null;

    /** Creates a new ReShadeChainTarget instance. */
    constructor($$source: Partial<ReShadeChainTarget> = {}) {
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("TargetRelativePath" in $$source)) {
            this["TargetRelativePath"] = "";
        }
        if (!("ExecutableRelativePath" in $$source)) {
            this["ExecutableRelativePath"] = "";
        }
        if (!("APIFamily" in $$source)) {
            this["APIFamily"] = injection$0.APIFamily.$zero;
        }
        if (!("PrimaryOwner" in $$source)) {
            this["PrimaryOwner"] = injection$0.Owner.$zero;
        }
        if (!("PrimaryProxyFilename" in $$source)) {
            this["PrimaryProxyFilename"] = "";
        }
        if (!("Status" in $$source)) {
            this["Status"] = injection$0.Status.$zero;
        }
        if (!("OptiScaler" in $$source)) {
            this["OptiScaler"] = null;
        }
        if (!("ReShade" in $$source)) {
            this["ReShade"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReShadeChainTarget instance from a string or object.
     */
    static createFrom($$source: any = {}): ReShadeChainTarget {
        const $$createField7_0 = $$createType35;
        const $$createField8_0 = $$createType37;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("OptiScaler" in $$parsedSource) {
            $$parsedSource["OptiScaler"] = $$createField7_0($$parsedSource["OptiScaler"]);
        }
        if ("ReShade" in $$parsedSource) {
            $$parsedSource["ReShade"] = $$createField8_0($$parsedSource["ReShade"]);
        }
        return new ReShadeChainTarget($$parsedSource as Partial<ReShadeChainTarget>);
    }
}

export const ReShadeContentCatalogue = reshade$0.ContentCatalogue;
export type ReShadeContentCatalogue = reshade$0.ContentCatalogue;

export class ReShadeDetectionResult {
    "Status": ReShadeDetectionStatus;
    "Targets": DetectedReShadeTarget[];
    "UnsupportedReason": string | null;

    /** Creates a new ReShadeDetectionResult instance. */
    constructor($$source: Partial<ReShadeDetectionResult> = {}) {
        if (!("Status" in $$source)) {
            this["Status"] = ReShadeDetectionStatus.$zero;
        }
        if (!("Targets" in $$source)) {
            this["Targets"] = [];
        }
        if (!("UnsupportedReason" in $$source)) {
            this["UnsupportedReason"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReShadeDetectionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ReShadeDetectionResult {
        const $$createField1_0 = $$createType39;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Targets" in $$parsedSource) {
            $$parsedSource["Targets"] = $$createField1_0($$parsedSource["Targets"]);
        }
        return new ReShadeDetectionResult($$parsedSource as Partial<ReShadeDetectionResult>);
    }
}

export enum ReShadeDetectionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ReShadeDetectionStatusInstalled = "installed",
    ReShadeDetectionStatusNotInstalled = "not_installed",
    ReShadeDetectionStatusUnsupported = "unsupported",
};

export const ReShadeDiscoveryResult = reshade$0.DiscoveryResult;
export type ReShadeDiscoveryResult = reshade$0.DiscoveryResult;

export const ReShadeInstallerStatus = reshade$0.InstallerStatus;
export type ReShadeInstallerStatus = reshade$0.InstallerStatus;

export class ReShadeOptiScalerChainState {
    "ProxyFilename": string;
    "Status": string;

    /** Creates a new ReShadeOptiScalerChainState instance. */
    constructor($$source: Partial<ReShadeOptiScalerChainState> = {}) {
        if (!("ProxyFilename" in $$source)) {
            this["ProxyFilename"] = "";
        }
        if (!("Status" in $$source)) {
            this["Status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReShadeOptiScalerChainState instance from a string or object.
     */
    static createFrom($$source: any = {}): ReShadeOptiScalerChainState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReShadeOptiScalerChainState($$parsedSource as Partial<ReShadeOptiScalerChainState>);
    }
}

export const ReShadePresetInspectionResult = reshade$0.PresetInspectionResult;
export type ReShadePresetInspectionResult = reshade$0.PresetInspectionResult;

export const ReShadePreview = reshade$0.Preview;
export type ReShadePreview = reshade$0.Preview;

export const ReShadeRecoveryState = reshade$0.RecoveryState;
export type ReShadeRecoveryState = reshade$0.RecoveryState;

export const ReShadeRequest = reshade$0.Request;
export type ReShadeRequest = reshade$0.Request;

export const ReShadeTarget = reshade$0.ManagedTarget;
export type ReShadeTarget = reshade$0.ManagedTarget;

export class ResolveImportSourceDuplicatesInput {
    "GameID": number;
    "Sources": ImportSourceRef[];

    /** Creates a new ResolveImportSourceDuplicatesInput instance. */
    constructor($$source: Partial<ResolveImportSourceDuplicatesInput> = {}) {
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("Sources" in $$source)) {
            this["Sources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolveImportSourceDuplicatesInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ResolveImportSourceDuplicatesInput {
        const $$createField1_0 = $$createType41;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Sources" in $$parsedSource) {
            $$parsedSource["Sources"] = $$createField1_0($$parsedSource["Sources"]);
        }
        return new ResolveImportSourceDuplicatesInput($$parsedSource as Partial<ResolveImportSourceDuplicatesInput>);
    }
}

export class ResolveImportSourceDuplicatesResult {
    "Items": ImportSourceDuplicateStatus[];

    /** Creates a new ResolveImportSourceDuplicatesResult instance. */
    constructor($$source: Partial<ResolveImportSourceDuplicatesResult> = {}) {
        if (!("Items" in $$source)) {
            this["Items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolveImportSourceDuplicatesResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ResolveImportSourceDuplicatesResult {
        const $$createField0_0 = $$createType43;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Items" in $$parsedSource) {
            $$parsedSource["Items"] = $$createField0_0($$parsedSource["Items"]);
        }
        return new ResolveImportSourceDuplicatesResult($$parsedSource as Partial<ResolveImportSourceDuplicatesResult>);
    }
}

export class RestoreMod {
    "ID": number;
    "Name": string;

    /** Creates a new RestoreMod instance. */
    constructor($$source: Partial<RestoreMod> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestoreMod instance from a string or object.
     */
    static createFrom($$source: any = {}): RestoreMod {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RestoreMod($$parsedSource as Partial<RestoreMod>);
    }
}

export class RestoreOperation {
    "Type": RestoreOperationType;
    "ManifestOperationIndex": number;
    "Mod": RestoreMod;
    "TargetPath": string;
    "BackupPath": string | null;

    /** Creates a new RestoreOperation instance. */
    constructor($$source: Partial<RestoreOperation> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = RestoreOperationType.$zero;
        }
        if (!("ManifestOperationIndex" in $$source)) {
            this["ManifestOperationIndex"] = 0;
        }
        if (!("Mod" in $$source)) {
            this["Mod"] = (new RestoreMod());
        }
        if (!("TargetPath" in $$source)) {
            this["TargetPath"] = "";
        }
        if (!("BackupPath" in $$source)) {
            this["BackupPath"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestoreOperation instance from a string or object.
     */
    static createFrom($$source: any = {}): RestoreOperation {
        const $$createField2_0 = $$createType44;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mod" in $$parsedSource) {
            $$parsedSource["Mod"] = $$createField2_0($$parsedSource["Mod"]);
        }
        return new RestoreOperation($$parsedSource as Partial<RestoreOperation>);
    }
}

export class RestoreOperationResult {
    "OperationIndex": number;
    "Operation": RestoreOperation;
    "Status": RestoreOperationStatus;
    "Message": string;
    "Error": string | null;

    /** Creates a new RestoreOperationResult instance. */
    constructor($$source: Partial<RestoreOperationResult> = {}) {
        if (!("OperationIndex" in $$source)) {
            this["OperationIndex"] = 0;
        }
        if (!("Operation" in $$source)) {
            this["Operation"] = (new RestoreOperation());
        }
        if (!("Status" in $$source)) {
            this["Status"] = RestoreOperationStatus.$zero;
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }
        if (!("Error" in $$source)) {
            this["Error"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestoreOperationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RestoreOperationResult {
        const $$createField1_0 = $$createType45;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Operation" in $$parsedSource) {
            $$parsedSource["Operation"] = $$createField1_0($$parsedSource["Operation"]);
        }
        return new RestoreOperationResult($$parsedSource as Partial<RestoreOperationResult>);
    }
}

export enum RestoreOperationStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RestoreOperationStatusCompleted = "completed",
    RestoreOperationStatusFailed = "failed",
    RestoreOperationStatusSkipped = "skipped",
};

export enum RestoreOperationType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RestoreOperationTypeRemoveAddedFile = "remove_added_file",
    RestoreOperationTypeRestoreReplacedFile = "restore_replaced_file",
    RestoreOperationTypeRemoveCreatedDir = "remove_created_directory",
    RestoreOperationTypeDeleteRestoredBackup = "delete_restored_backup",
};

export class RestoreResult {
    "Success": boolean;
    "CompletedCount": number;
    "FailedCount": number;
    "SkippedCount": number;
    "Results": RestoreOperationResult[];

    /** Creates a new RestoreResult instance. */
    constructor($$source: Partial<RestoreResult> = {}) {
        if (!("Success" in $$source)) {
            this["Success"] = false;
        }
        if (!("CompletedCount" in $$source)) {
            this["CompletedCount"] = 0;
        }
        if (!("FailedCount" in $$source)) {
            this["FailedCount"] = 0;
        }
        if (!("SkippedCount" in $$source)) {
            this["SkippedCount"] = 0;
        }
        if (!("Results" in $$source)) {
            this["Results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestoreResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RestoreResult {
        const $$createField4_0 = $$createType47;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Results" in $$parsedSource) {
            $$parsedSource["Results"] = $$createField4_0($$parsedSource["Results"]);
        }
        return new RestoreResult($$parsedSource as Partial<RestoreResult>);
    }
}

export class SourceScanResult {
    "Inserted": number;
    "Updated": number;
    "MarkedUnavailable": number;
    "Games": StoredGame[];

    /** Creates a new SourceScanResult instance. */
    constructor($$source: Partial<SourceScanResult> = {}) {
        if (!("Inserted" in $$source)) {
            this["Inserted"] = 0;
        }
        if (!("Updated" in $$source)) {
            this["Updated"] = 0;
        }
        if (!("MarkedUnavailable" in $$source)) {
            this["MarkedUnavailable"] = 0;
        }
        if (!("Games" in $$source)) {
            this["Games"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceScanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SourceScanResult {
        const $$createField3_0 = $$createType49;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Games" in $$parsedSource) {
            $$parsedSource["Games"] = $$createField3_0($$parsedSource["Games"]);
        }
        return new SourceScanResult($$parsedSource as Partial<SourceScanResult>);
    }
}

export class StateComparison {
    "AppliedMatchesCurrent": boolean;
    "AppliedMatchesDesired": boolean;
    "CurrentMatchesDesired": boolean;

    /** Creates a new StateComparison instance. */
    constructor($$source: Partial<StateComparison> = {}) {
        if (!("AppliedMatchesCurrent" in $$source)) {
            this["AppliedMatchesCurrent"] = false;
        }
        if (!("AppliedMatchesDesired" in $$source)) {
            this["AppliedMatchesDesired"] = false;
        }
        if (!("CurrentMatchesDesired" in $$source)) {
            this["CurrentMatchesDesired"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StateComparison instance from a string or object.
     */
    static createFrom($$source: any = {}): StateComparison {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StateComparison($$parsedSource as Partial<StateComparison>);
    }
}

export class StoredGame {
    "ID": number;
    "Name": string;
    "InstallPath": string;
    "Source": string;
    "SourceID": string | null;
    "Available": boolean;
    "LastSeenAt": string | null;
    "ModStoragePath": string | null;
    "ModStoragePathOverride": string | null;

    /** Creates a new StoredGame instance. */
    constructor($$source: Partial<StoredGame> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("InstallPath" in $$source)) {
            this["InstallPath"] = "";
        }
        if (!("Source" in $$source)) {
            this["Source"] = "";
        }
        if (!("SourceID" in $$source)) {
            this["SourceID"] = null;
        }
        if (!("Available" in $$source)) {
            this["Available"] = false;
        }
        if (!("LastSeenAt" in $$source)) {
            this["LastSeenAt"] = null;
        }
        if (!("ModStoragePath" in $$source)) {
            this["ModStoragePath"] = null;
        }
        if (!("ModStoragePathOverride" in $$source)) {
            this["ModStoragePathOverride"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StoredGame instance from a string or object.
     */
    static createFrom($$source: any = {}): StoredGame {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StoredGame($$parsedSource as Partial<StoredGame>);
    }
}

export class StrategyDescriptor {
    "Type": StrategyType;
    "Label": string;
    "Description": string;
    "Visibility": StrategyVisibility;
    "RequiresTargetPath": boolean;
    "SupportsTargetDetection": boolean;

    /** Creates a new StrategyDescriptor instance. */
    constructor($$source: Partial<StrategyDescriptor> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = StrategyType.$zero;
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("Visibility" in $$source)) {
            this["Visibility"] = StrategyVisibility.$zero;
        }
        if (!("RequiresTargetPath" in $$source)) {
            this["RequiresTargetPath"] = false;
        }
        if (!("SupportsTargetDetection" in $$source)) {
            this["SupportsTargetDetection"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StrategyDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): StrategyDescriptor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StrategyDescriptor($$parsedSource as Partial<StrategyDescriptor>);
    }
}

export enum StrategyType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StrategyTypeGenericCopy = "generic_copy",
    StrategyTypeBepInEx = "bepinex",
    StrategyTypeUnrealPak = "unreal_pak",
};

export enum StrategyVisibility {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StrategyVisibilitySelectable = "selectable",
    StrategyVisibilityDisabled = "disabled",
    StrategyVisibilityInternal = "internal",
};

export class Tag {
    "ID": number;
    "GameID": number;
    "Name": string;
    "Color": TagColor;

    /** Creates a new Tag instance. */
    constructor($$source: Partial<Tag> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Color" in $$source)) {
            this["Color"] = TagColor.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tag instance from a string or object.
     */
    static createFrom($$source: any = {}): Tag {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tag($$parsedSource as Partial<Tag>);
    }
}

export enum TagColor {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TagColorRed = "red",
    TagColorOrange = "orange",
    TagColorYellow = "yellow",
    TagColorGreen = "green",
    TagColorTeal = "teal",
    TagColorBlue = "blue",
    TagColorPurple = "purple",
    TagColorPink = "pink",
};

export class TextDiffLine {
    "Kind": string;
    "Line": string;
    "LineNo": number;

    /** Creates a new TextDiffLine instance. */
    constructor($$source: Partial<TextDiffLine> = {}) {
        if (!("Kind" in $$source)) {
            this["Kind"] = "";
        }
        if (!("Line" in $$source)) {
            this["Line"] = "";
        }
        if (!("LineNo" in $$source)) {
            this["LineNo"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TextDiffLine instance from a string or object.
     */
    static createFrom($$source: any = {}): TextDiffLine {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TextDiffLine($$parsedSource as Partial<TextDiffLine>);
    }
}

export class UpdateModDetailsInput {
    "ModID": number;
    "Name": string;
    "Metadata": UpdateModMetadataInput;
    "TagIDs": number[];
    "NewTags": CreateTagInput[];

    /** Creates a new UpdateModDetailsInput instance. */
    constructor($$source: Partial<UpdateModDetailsInput> = {}) {
        if (!("ModID" in $$source)) {
            this["ModID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Metadata" in $$source)) {
            this["Metadata"] = (new UpdateModMetadataInput());
        }
        if (!("TagIDs" in $$source)) {
            this["TagIDs"] = [];
        }
        if (!("NewTags" in $$source)) {
            this["NewTags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateModDetailsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateModDetailsInput {
        const $$createField2_0 = $$createType50;
        const $$createField3_0 = $$createType23;
        const $$createField4_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Metadata" in $$parsedSource) {
            $$parsedSource["Metadata"] = $$createField2_0($$parsedSource["Metadata"]);
        }
        if ("TagIDs" in $$parsedSource) {
            $$parsedSource["TagIDs"] = $$createField3_0($$parsedSource["TagIDs"]);
        }
        if ("NewTags" in $$parsedSource) {
            $$parsedSource["NewTags"] = $$createField4_0($$parsedSource["NewTags"]);
        }
        return new UpdateModDetailsInput($$parsedSource as Partial<UpdateModDetailsInput>);
    }
}

export class UpdateModInput {
    "ModID": number;
    "SourceType": ModSourceType;
    "SourcePath": string;

    /** Creates a new UpdateModInput instance. */
    constructor($$source: Partial<UpdateModInput> = {}) {
        if (!("ModID" in $$source)) {
            this["ModID"] = 0;
        }
        if (!("SourceType" in $$source)) {
            this["SourceType"] = ModSourceType.$zero;
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateModInput instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateModInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateModInput($$parsedSource as Partial<UpdateModInput>);
    }
}

export class UpdateModMetadataInput {
    "ModID": number;
    "Version": ModMetadataFieldUpdate;
    "Author": ModMetadataFieldUpdate;
    "Description": ModMetadataFieldUpdate;
    "SourceURL": ModMetadataFieldUpdate;
    "Notes": string | null;

    /** Creates a new UpdateModMetadataInput instance. */
    constructor($$source: Partial<UpdateModMetadataInput> = {}) {
        if (!("ModID" in $$source)) {
            this["ModID"] = 0;
        }
        if (!("Version" in $$source)) {
            this["Version"] = (new ModMetadataFieldUpdate());
        }
        if (!("Author" in $$source)) {
            this["Author"] = (new ModMetadataFieldUpdate());
        }
        if (!("Description" in $$source)) {
            this["Description"] = (new ModMetadataFieldUpdate());
        }
        if (!("SourceURL" in $$source)) {
            this["SourceURL"] = (new ModMetadataFieldUpdate());
        }
        if (!("Notes" in $$source)) {
            this["Notes"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateModMetadataInput instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateModMetadataInput {
        const $$createField1_0 = $$createType51;
        const $$createField2_0 = $$createType51;
        const $$createField3_0 = $$createType51;
        const $$createField4_0 = $$createType51;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Version" in $$parsedSource) {
            $$parsedSource["Version"] = $$createField1_0($$parsedSource["Version"]);
        }
        if ("Author" in $$parsedSource) {
            $$parsedSource["Author"] = $$createField2_0($$parsedSource["Author"]);
        }
        if ("Description" in $$parsedSource) {
            $$parsedSource["Description"] = $$createField3_0($$parsedSource["Description"]);
        }
        if ("SourceURL" in $$parsedSource) {
            $$parsedSource["SourceURL"] = $$createField4_0($$parsedSource["SourceURL"]);
        }
        return new UpdateModMetadataInput($$parsedSource as Partial<UpdateModMetadataInput>);
    }
}

export class UpdateModResult {
    "Mod": Mod;
    "Before": ModPackageSnapshot;
    "After": ModPackageSnapshot;
    "MetadataWarning": string | null;
    "Warnings": string[];
    "IsInAppliedProfile": boolean;
    "RequiresReapply": boolean;

    /** Creates a new UpdateModResult instance. */
    constructor($$source: Partial<UpdateModResult> = {}) {
        if (!("Mod" in $$source)) {
            this["Mod"] = (new Mod());
        }
        if (!("Before" in $$source)) {
            this["Before"] = (new ModPackageSnapshot());
        }
        if (!("After" in $$source)) {
            this["After"] = (new ModPackageSnapshot());
        }
        if (!("MetadataWarning" in $$source)) {
            this["MetadataWarning"] = null;
        }
        if (!("Warnings" in $$source)) {
            this["Warnings"] = [];
        }
        if (!("IsInAppliedProfile" in $$source)) {
            this["IsInAppliedProfile"] = false;
        }
        if (!("RequiresReapply" in $$source)) {
            this["RequiresReapply"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateModResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateModResult {
        const $$createField0_0 = $$createType26;
        const $$createField1_0 = $$createType52;
        const $$createField2_0 = $$createType52;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mod" in $$parsedSource) {
            $$parsedSource["Mod"] = $$createField0_0($$parsedSource["Mod"]);
        }
        if ("Before" in $$parsedSource) {
            $$parsedSource["Before"] = $$createField1_0($$parsedSource["Before"]);
        }
        if ("After" in $$parsedSource) {
            $$parsedSource["After"] = $$createField2_0($$parsedSource["After"]);
        }
        if ("Warnings" in $$parsedSource) {
            $$parsedSource["Warnings"] = $$createField4_0($$parsedSource["Warnings"]);
        }
        return new UpdateModResult($$parsedSource as Partial<UpdateModResult>);
    }
}

export class WriterEntryDTO {
    "Order": number;
    "SourceKind": string;
    "SourceID": string;
    "ModID": number | null;
    "ModName": string;
    "LoadOrder": number;
    "DisplayLoadOrder": number;
    "IsWinner": boolean;
    "WouldWrite": boolean;

    /** Creates a new WriterEntryDTO instance. */
    constructor($$source: Partial<WriterEntryDTO> = {}) {
        if (!("Order" in $$source)) {
            this["Order"] = 0;
        }
        if (!("SourceKind" in $$source)) {
            this["SourceKind"] = "";
        }
        if (!("SourceID" in $$source)) {
            this["SourceID"] = "";
        }
        if (!("ModID" in $$source)) {
            this["ModID"] = null;
        }
        if (!("ModName" in $$source)) {
            this["ModName"] = "";
        }
        if (!("LoadOrder" in $$source)) {
            this["LoadOrder"] = 0;
        }
        if (!("DisplayLoadOrder" in $$source)) {
            this["DisplayLoadOrder"] = 0;
        }
        if (!("IsWinner" in $$source)) {
            this["IsWinner"] = false;
        }
        if (!("WouldWrite" in $$source)) {
            this["WouldWrite"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WriterEntryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WriterEntryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WriterEntryDTO($$parsedSource as Partial<WriterEntryDTO>);
    }
}

// Private type creation functions
const $$createType0 = FourStateView.createFrom;
const $$createType1 = WriterEntryDTO.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = StateComparison.createFrom;
const $$createType5 = InspectionSideMetadata.createFrom;
const $$createType6 = TextDiffLine.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = PEMetadata.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = ImageMetadata.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = ArchiveEntry.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = DeploymentSummary.createFrom;
const $$createType15 = DeploymentTreeNode.createFrom;
const $$createType16 = $Create.Map($Create.Any, $Create.Any);
const $$createType17 = $Create.Array($$createType15);
const $$createType18 = $Create.Map($Create.Any, $Create.Any);
const $$createType19 = DiagnosticLogEntry.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = FileStateView.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = $Create.Array($Create.Any);
const $$createType24 = CreateTagInput.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = Mod.createFrom;
const $$createType27 = ModInstallConfig.createFrom;
const $$createType28 = ModMetadata.createFrom;
const $$createType29 = $Create.Nullable($$createType28);
const $$createType30 = Tag.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = ModMetadataField.createFrom;
const $$createType33 = ModDetectedMetadataSnapshot.createFrom;
const $$createType34 = ReShadeOptiScalerChainState.createFrom;
const $$createType35 = $Create.Nullable($$createType34);
const $$createType36 = ReShadeChainState.createFrom;
const $$createType37 = $Create.Nullable($$createType36);
const $$createType38 = DetectedReShadeTarget.createFrom;
const $$createType39 = $Create.Array($$createType38);
const $$createType40 = ImportSourceRef.createFrom;
const $$createType41 = $Create.Array($$createType40);
const $$createType42 = ImportSourceDuplicateStatus.createFrom;
const $$createType43 = $Create.Array($$createType42);
const $$createType44 = RestoreMod.createFrom;
const $$createType45 = RestoreOperation.createFrom;
const $$createType46 = RestoreOperationResult.createFrom;
const $$createType47 = $Create.Array($$createType46);
const $$createType48 = StoredGame.createFrom;
const $$createType49 = $Create.Array($$createType48);
const $$createType50 = UpdateModMetadataInput.createFrom;
const $$createType51 = ModMetadataFieldUpdate.createFrom;
const $$createType52 = ModPackageSnapshot.createFrom;
