// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ModProfile {
    "ID": number;
    "GameID": number;
    "Name": string;
    "IsActive": boolean;
    "CreatedAt": string;
    "UpdatedAt": string;

    /** Creates a new ModProfile instance. */
    constructor($$source: Partial<ModProfile> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("IsActive" in $$source)) {
            this["IsActive"] = false;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = "";
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): ModProfile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModProfile($$parsedSource as Partial<ModProfile>);
    }
}

export class SteamScanResult {
    "Inserted": number;
    "Updated": number;
    "MarkedUnavailable": number;
    "Games": StoredGame[];

    /** Creates a new SteamScanResult instance. */
    constructor($$source: Partial<SteamScanResult> = {}) {
        if (!("Inserted" in $$source)) {
            this["Inserted"] = 0;
        }
        if (!("Updated" in $$source)) {
            this["Updated"] = 0;
        }
        if (!("MarkedUnavailable" in $$source)) {
            this["MarkedUnavailable"] = 0;
        }
        if (!("Games" in $$source)) {
            this["Games"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SteamScanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SteamScanResult {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Games" in $$parsedSource) {
            $$parsedSource["Games"] = $$createField3_0($$parsedSource["Games"]);
        }
        return new SteamScanResult($$parsedSource as Partial<SteamScanResult>);
    }
}

export class StoredGame {
    "ID": number;
    "Name": string;
    "InstallPath": string;
    "Source": string;
    "SourceID": string;
    "Available": boolean;
    "LastSeenAt": string;

    /** Creates a new StoredGame instance. */
    constructor($$source: Partial<StoredGame> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("InstallPath" in $$source)) {
            this["InstallPath"] = "";
        }
        if (!("Source" in $$source)) {
            this["Source"] = "";
        }
        if (!("SourceID" in $$source)) {
            this["SourceID"] = "";
        }
        if (!("Available" in $$source)) {
            this["Available"] = false;
        }
        if (!("LastSeenAt" in $$source)) {
            this["LastSeenAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StoredGame instance from a string or object.
     */
    static createFrom($$source: any = {}): StoredGame {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StoredGame($$parsedSource as Partial<StoredGame>);
    }
}

// Private type creation functions
const $$createType0 = StoredGame.createFrom;
const $$createType1 = $Create.Array($$createType0);
