// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Mod {
    "ID": number;
    "GameID": number;
    "Name": string;
    "SourceType": ModSourceType;
    "SourcePath": string;
    "OriginalSourcePath": string;
    "OriginalSourceName": string | null;
    "CreatedAt": string;
    "UpdatedAt": string;

    /** Creates a new Mod instance. */
    constructor($$source: Partial<Mod> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("SourceType" in $$source)) {
            this["SourceType"] = ModSourceType.$zero;
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }
        if (!("OriginalSourcePath" in $$source)) {
            this["OriginalSourcePath"] = "";
        }
        if (!("OriginalSourceName" in $$source)) {
            this["OriginalSourceName"] = null;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = "";
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Mod instance from a string or object.
     */
    static createFrom($$source: any = {}): Mod {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Mod($$parsedSource as Partial<Mod>);
    }
}

export class ModProfile {
    "ID": number;
    "GameID": number;
    "Name": string;
    "IsActive": boolean;
    "CreatedAt": string;
    "UpdatedAt": string;

    /** Creates a new ModProfile instance. */
    constructor($$source: Partial<ModProfile> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("IsActive" in $$source)) {
            this["IsActive"] = false;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = "";
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): ModProfile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModProfile($$parsedSource as Partial<ModProfile>);
    }
}

export enum ModSourceType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ModSourceTypeFolder = "folder",
    ModSourceTypeArchive = "archive",
};

export class ProfileMod {
    "ProfileID": number;
    "ModID": number;
    "Name": string;
    "SourcePath": string;
    "Enabled": boolean;
    "LoadOrder": number;
    "CreatedAt": string;
    "UpdatedAt": string;

    /** Creates a new ProfileMod instance. */
    constructor($$source: Partial<ProfileMod> = {}) {
        if (!("ProfileID" in $$source)) {
            this["ProfileID"] = 0;
        }
        if (!("ModID" in $$source)) {
            this["ModID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }
        if (!("Enabled" in $$source)) {
            this["Enabled"] = false;
        }
        if (!("LoadOrder" in $$source)) {
            this["LoadOrder"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = "";
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileMod instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileMod {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileMod($$parsedSource as Partial<ProfileMod>);
    }
}

export class SteamScanResult {
    "Inserted": number;
    "Updated": number;
    "MarkedUnavailable": number;
    "Games": StoredGame[];

    /** Creates a new SteamScanResult instance. */
    constructor($$source: Partial<SteamScanResult> = {}) {
        if (!("Inserted" in $$source)) {
            this["Inserted"] = 0;
        }
        if (!("Updated" in $$source)) {
            this["Updated"] = 0;
        }
        if (!("MarkedUnavailable" in $$source)) {
            this["MarkedUnavailable"] = 0;
        }
        if (!("Games" in $$source)) {
            this["Games"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SteamScanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SteamScanResult {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Games" in $$parsedSource) {
            $$parsedSource["Games"] = $$createField3_0($$parsedSource["Games"]);
        }
        return new SteamScanResult($$parsedSource as Partial<SteamScanResult>);
    }
}

export class StoredGame {
    "ID": number;
    "Name": string;
    "InstallPath": string;
    "Source": string;
    "SourceID": string | null;
    "Available": boolean;
    "LastSeenAt": string | null;
    "ModStoragePath": string | null;
    "ModStoragePathOverride": string | null;

    /** Creates a new StoredGame instance. */
    constructor($$source: Partial<StoredGame> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("InstallPath" in $$source)) {
            this["InstallPath"] = "";
        }
        if (!("Source" in $$source)) {
            this["Source"] = "";
        }
        if (!("SourceID" in $$source)) {
            this["SourceID"] = null;
        }
        if (!("Available" in $$source)) {
            this["Available"] = false;
        }
        if (!("LastSeenAt" in $$source)) {
            this["LastSeenAt"] = null;
        }
        if (!("ModStoragePath" in $$source)) {
            this["ModStoragePath"] = null;
        }
        if (!("ModStoragePathOverride" in $$source)) {
            this["ModStoragePathOverride"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StoredGame instance from a string or object.
     */
    static createFrom($$source: any = {}): StoredGame {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StoredGame($$parsedSource as Partial<StoredGame>);
    }
}

// Private type creation functions
const $$createType0 = StoredGame.createFrom;
const $$createType1 = $Create.Array($$createType0);
