// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ModContext {
    "ModID": number;
    "ModName": string;

    /** Creates a new ModContext instance. */
    constructor($$source: Partial<ModContext> = {}) {
        if (!("ModID" in $$source)) {
            this["ModID"] = 0;
        }
        if (!("ModName" in $$source)) {
            this["ModName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModContext instance from a string or object.
     */
    static createFrom($$source: any = {}): ModContext {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModContext($$parsedSource as Partial<ModContext>);
    }
}

export class Operation {
    "Type": OperationType;
    "SourcePath": string | null;
    "TargetPath": string;
    "BackupPath": string | null;
    "Conflict": boolean;
    "Mod": ModContext;

    /** Creates a new Operation instance. */
    constructor($$source: Partial<Operation> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = OperationType.$zero;
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = null;
        }
        if (!("TargetPath" in $$source)) {
            this["TargetPath"] = "";
        }
        if (!("BackupPath" in $$source)) {
            this["BackupPath"] = null;
        }
        if (!("Conflict" in $$source)) {
            this["Conflict"] = false;
        }
        if (!("Mod" in $$source)) {
            this["Mod"] = (new ModContext());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Operation instance from a string or object.
     */
    static createFrom($$source: any = {}): Operation {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mod" in $$parsedSource) {
            $$parsedSource["Mod"] = $$createField5_0($$parsedSource["Mod"]);
        }
        return new Operation($$parsedSource as Partial<Operation>);
    }
}

export class OperationPlan {
    "Operations": Operation[];
    "Issues": PlanIssue[];
    "CanApply": boolean;

    /** Creates a new OperationPlan instance. */
    constructor($$source: Partial<OperationPlan> = {}) {
        if (!("Operations" in $$source)) {
            this["Operations"] = [];
        }
        if (!("Issues" in $$source)) {
            this["Issues"] = [];
        }
        if (!("CanApply" in $$source)) {
            this["CanApply"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OperationPlan instance from a string or object.
     */
    static createFrom($$source: any = {}): OperationPlan {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Operations" in $$parsedSource) {
            $$parsedSource["Operations"] = $$createField0_0($$parsedSource["Operations"]);
        }
        if ("Issues" in $$parsedSource) {
            $$parsedSource["Issues"] = $$createField1_0($$parsedSource["Issues"]);
        }
        return new OperationPlan($$parsedSource as Partial<OperationPlan>);
    }
}

export enum OperationType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OperationTypeCopy = "copy",
    OperationTypeReplace = "replace",
    OperationTypeCreateDirectory = "create_directory",
};

export class PlanIssue {
    "Severity": PlanIssueSeverity;
    "Kind": PlanIssueKind;
    "Message": string;
    "ProfileID": number;
    "SourcePath": string | null;
    "TargetPath": string | null;
    "Mod": ModContext | null;

    /** Creates a new PlanIssue instance. */
    constructor($$source: Partial<PlanIssue> = {}) {
        if (!("Severity" in $$source)) {
            this["Severity"] = PlanIssueSeverity.$zero;
        }
        if (!("Kind" in $$source)) {
            this["Kind"] = PlanIssueKind.$zero;
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }
        if (!("ProfileID" in $$source)) {
            this["ProfileID"] = 0;
        }
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = null;
        }
        if (!("TargetPath" in $$source)) {
            this["TargetPath"] = null;
        }
        if (!("Mod" in $$source)) {
            this["Mod"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlanIssue instance from a string or object.
     */
    static createFrom($$source: any = {}): PlanIssue {
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mod" in $$parsedSource) {
            $$parsedSource["Mod"] = $$createField6_0($$parsedSource["Mod"]);
        }
        return new PlanIssue($$parsedSource as Partial<PlanIssue>);
    }
}

export enum PlanIssueKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PlanIssueMissingManagedSourcePath = "missing_managed_source_path",
    PlanIssueMissingInstallConfig = "missing_install_config",
    PlanIssueIncompleteInstallConfig = "incomplete_install_config",
    PlanIssueMissingGameInstallPath = "missing_game_install_path",
    PlanIssueMissingGameInstallDir = "missing_game_install_directory",
    PlanIssueGameInstallPathNotDir = "game_install_path_not_directory",
    PlanIssueMissingSourceRoot = "missing_source_root",
    PlanIssueSourceRootNotDirectory = "source_root_not_directory",
    PlanIssueMissingGameModStorage = "missing_game_mod_storage_path",
    PlanIssueTargetDirectoryPathFile = "target_directory_path_is_file",
    PlanIssueTargetFilePathDirectory = "target_file_path_is_directory",
    PlanIssueTargetPathConflict = "target_path_conflict",
    PlanIssueReplaceExistingTarget = "replace_existing_target",
};

export enum PlanIssueSeverity {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PlanIssueSeverityError = "error",
    PlanIssueSeverityWarning = "warning",
};

// Private type creation functions
const $$createType0 = ModContext.createFrom;
const $$createType1 = Operation.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = PlanIssue.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Nullable($$createType0);
