// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Mod {
    "ID": number;
    "Name": string;

    /** Creates a new Mod instance. */
    constructor($$source: Partial<Mod> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Mod instance from a string or object.
     */
    static createFrom($$source: any = {}): Mod {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Mod($$parsedSource as Partial<Mod>);
    }
}

export class RestoreOperation {
    "Type": RestoreOperationType;
    "ManifestOperationIndex": number;
    "Mod": Mod;
    "TargetPath": string;
    "BackupPath": string | null;

    /** Creates a new RestoreOperation instance. */
    constructor($$source: Partial<RestoreOperation> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = RestoreOperationType.$zero;
        }
        if (!("ManifestOperationIndex" in $$source)) {
            this["ManifestOperationIndex"] = 0;
        }
        if (!("Mod" in $$source)) {
            this["Mod"] = (new Mod());
        }
        if (!("TargetPath" in $$source)) {
            this["TargetPath"] = "";
        }
        if (!("BackupPath" in $$source)) {
            this["BackupPath"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestoreOperation instance from a string or object.
     */
    static createFrom($$source: any = {}): RestoreOperation {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mod" in $$parsedSource) {
            $$parsedSource["Mod"] = $$createField2_0($$parsedSource["Mod"]);
        }
        return new RestoreOperation($$parsedSource as Partial<RestoreOperation>);
    }
}

export class RestoreOperationResult {
    "OperationIndex": number;
    "Operation": RestoreOperation;
    "Status": RestoreOperationStatus;
    "Message": string;
    "Error": string | null;

    /** Creates a new RestoreOperationResult instance. */
    constructor($$source: Partial<RestoreOperationResult> = {}) {
        if (!("OperationIndex" in $$source)) {
            this["OperationIndex"] = 0;
        }
        if (!("Operation" in $$source)) {
            this["Operation"] = (new RestoreOperation());
        }
        if (!("Status" in $$source)) {
            this["Status"] = RestoreOperationStatus.$zero;
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }
        if (!("Error" in $$source)) {
            this["Error"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestoreOperationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RestoreOperationResult {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Operation" in $$parsedSource) {
            $$parsedSource["Operation"] = $$createField1_0($$parsedSource["Operation"]);
        }
        return new RestoreOperationResult($$parsedSource as Partial<RestoreOperationResult>);
    }
}

export enum RestoreOperationStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RestoreOperationStatusCompleted = "completed",
    RestoreOperationStatusFailed = "failed",
    RestoreOperationStatusSkipped = "skipped",
};

export enum RestoreOperationType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RestoreOperationTypeRemoveAddedFile = "remove_added_file",
    RestoreOperationTypeRestoreReplacedFile = "restore_replaced_file",
    RestoreOperationTypeRemoveCreatedDir = "remove_created_directory",
    RestoreOperationTypeDeleteRestoredBackup = "delete_restored_backup",
};

export class RestoreResult {
    "Success": boolean;
    "CompletedCount": number;
    "FailedCount": number;
    "SkippedCount": number;
    "Results": RestoreOperationResult[];

    /** Creates a new RestoreResult instance. */
    constructor($$source: Partial<RestoreResult> = {}) {
        if (!("Success" in $$source)) {
            this["Success"] = false;
        }
        if (!("CompletedCount" in $$source)) {
            this["CompletedCount"] = 0;
        }
        if (!("FailedCount" in $$source)) {
            this["FailedCount"] = 0;
        }
        if (!("SkippedCount" in $$source)) {
            this["SkippedCount"] = 0;
        }
        if (!("Results" in $$source)) {
            this["Results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestoreResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RestoreResult {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Results" in $$parsedSource) {
            $$parsedSource["Results"] = $$createField4_0($$parsedSource["Results"]);
        }
        return new RestoreResult($$parsedSource as Partial<RestoreResult>);
    }
}

// Private type creation functions
const $$createType0 = Mod.createFrom;
const $$createType1 = RestoreOperation.createFrom;
const $$createType2 = RestoreOperationResult.createFrom;
const $$createType3 = $Create.Array($$createType2);
