// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    Action,
    ApplyResult,
    Architecture,
    BuildVariant,
    Drift,
    InstallerProvenance,
    ManagedFile,
    ManagedTarget,
    ManagementStatus,
    Manifest,
    Operation,
    Ownership,
    Preview,
    RecoveryState,
    RenderingAPI,
    Request,
    TargetState
} from "./models.js";
