// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    APIProxyOptions,
    Action,
    ApplyResult,
    Architecture,
    BuildVariant,
    Candidate,
    DiscoveryResult,
    DiscoveryWarning,
    Drift,
    InstallerProvenance,
    ManagedFile,
    ManagedTarget,
    ManagementStatus,
    Manifest,
    Operation,
    Ownership,
    PathImpact,
    PathRole,
    Preview,
    ProxyEvidence,
    RecoveryState,
    RenderingAPI,
    Request,
    TargetState,
    UserContent,
    UserContentDrift,
    VariantProvenance
} from "./models.js";
