// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as filetxn$0 from "../filetxn/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export enum Action {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ActionInstall = "install",
    ActionAdopt = "adopt",
    ActionUpdate = "update",
    ActionRepair = "repair",
    ActionUninstall = "uninstall",
};

export class ApplyResult {
    "success": boolean;
    "rolledBack": boolean;
    "message": string;

    /** Creates a new ApplyResult instance. */
    constructor($$source: Partial<ApplyResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("rolledBack" in $$source)) {
            this["rolledBack"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplyResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ApplyResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApplyResult($$parsedSource as Partial<ApplyResult>);
    }
}

export enum Architecture {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ArchitectureX86 = "x86",
    ArchitectureX64 = "x64",
};

export enum BuildVariant {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    BuildVariantStandard = "standard",
    BuildVariantAddon = "addon",
};

export class Drift {
    "relativePath": string;
    "expectedHash": string;
    "actualHash"?: string;
    "missing": boolean;

    /** Creates a new Drift instance. */
    constructor($$source: Partial<Drift> = {}) {
        if (!("relativePath" in $$source)) {
            this["relativePath"] = "";
        }
        if (!("expectedHash" in $$source)) {
            this["expectedHash"] = "";
        }
        if (!("missing" in $$source)) {
            this["missing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Drift instance from a string or object.
     */
    static createFrom($$source: any = {}): Drift {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Drift($$parsedSource as Partial<Drift>);
    }
}

export class InstallerProvenance {
    "tag"?: string | null;
    "assetName"?: string | null;
    "url"?: string | null;
    "digest"?: string | null;
    "size"?: number | null;

    /** Creates a new InstallerProvenance instance. */
    constructor($$source: Partial<InstallerProvenance> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallerProvenance instance from a string or object.
     */
    static createFrom($$source: any = {}): InstallerProvenance {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstallerProvenance($$parsedSource as Partial<InstallerProvenance>);
    }
}

export class ManagedFile {
    "relativePath": string;
    "sha256": string;
    "sizeBytes": number;
    "ownership": Ownership;
    "backupPath"?: string | null;
    "backupSha256"?: string | null;
    "backupSizeBytes"?: number | null;

    /** Creates a new ManagedFile instance. */
    constructor($$source: Partial<ManagedFile> = {}) {
        if (!("relativePath" in $$source)) {
            this["relativePath"] = "";
        }
        if (!("sha256" in $$source)) {
            this["sha256"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }
        if (!("ownership" in $$source)) {
            this["ownership"] = Ownership.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManagedFile instance from a string or object.
     */
    static createFrom($$source: any = {}): ManagedFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ManagedFile($$parsedSource as Partial<ManagedFile>);
    }
}

export class ManagedTarget {
    "ID": number;
    "GameID": number;
    "TargetRelativePath": string;
    "ExecutableRelativePath": string;
    "RenderingAPI": RenderingAPI;
    "ProxyFilename": string;
    "Architecture": Architecture;
    "BuildVariant": BuildVariant;
    "RuntimeVersion": string;
    "Provenance": InstallerProvenance;
    "ManagementOrigin": string;
    "Status": ManagementStatus;
    "CreatedAt": string;
    "UpdatedAt": string;
    "LastVerifiedAt": string | null;

    /** Creates a new ManagedTarget instance. */
    constructor($$source: Partial<ManagedTarget> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("TargetRelativePath" in $$source)) {
            this["TargetRelativePath"] = "";
        }
        if (!("ExecutableRelativePath" in $$source)) {
            this["ExecutableRelativePath"] = "";
        }
        if (!("RenderingAPI" in $$source)) {
            this["RenderingAPI"] = RenderingAPI.$zero;
        }
        if (!("ProxyFilename" in $$source)) {
            this["ProxyFilename"] = "";
        }
        if (!("Architecture" in $$source)) {
            this["Architecture"] = Architecture.$zero;
        }
        if (!("BuildVariant" in $$source)) {
            this["BuildVariant"] = BuildVariant.$zero;
        }
        if (!("RuntimeVersion" in $$source)) {
            this["RuntimeVersion"] = "";
        }
        if (!("Provenance" in $$source)) {
            this["Provenance"] = (new InstallerProvenance());
        }
        if (!("ManagementOrigin" in $$source)) {
            this["ManagementOrigin"] = "";
        }
        if (!("Status" in $$source)) {
            this["Status"] = ManagementStatus.$zero;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = "";
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = "";
        }
        if (!("LastVerifiedAt" in $$source)) {
            this["LastVerifiedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManagedTarget instance from a string or object.
     */
    static createFrom($$source: any = {}): ManagedTarget {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Provenance" in $$parsedSource) {
            $$parsedSource["Provenance"] = $$createField9_0($$parsedSource["Provenance"]);
        }
        return new ManagedTarget($$parsedSource as Partial<ManagedTarget>);
    }
}

export enum ManagementStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ManagementStatusUnmanaged = "unmanaged",
    ManagementStatusManaged = "managed",
    ManagementStatusDrifted = "drifted",
    ManagementStatusRecoveryRequired = "recovery_required",
    ManagementStatusIncompatibleManifest = "incompatible_manifest",
};

export class Manifest {
    "version": number;
    "files": ManagedFile[];
    "hasPreAdoptionRollbackData": boolean;

    /** Creates a new Manifest instance. */
    constructor($$source: Partial<Manifest> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("hasPreAdoptionRollbackData" in $$source)) {
            this["hasPreAdoptionRollbackData"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manifest instance from a string or object.
     */
    static createFrom($$source: any = {}): Manifest {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField1_0($$parsedSource["files"]);
        }
        return new Manifest($$parsedSource as Partial<Manifest>);
    }
}

export const Operation = filetxn$0.Operation;
export type Operation = filetxn$0.Operation;

export enum Ownership {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OwnershipManaged = "managed",
    OwnershipAdopted = "adopted",
    OwnershipUser = "user",
    OwnershipForeign = "foreign",
};

export class Preview {
    "request": Request;
    "operations": Operation[];
    "warnings": string[];
    "conflicts": string[];
    "drift": Drift[];
    "desiredTarget"?: TargetState | null;
    "previewHash": string;
    "canApply": boolean;

    /** Creates a new Preview instance. */
    constructor($$source: Partial<Preview> = {}) {
        if (!("request" in $$source)) {
            this["request"] = (new Request());
        }
        if (!("operations" in $$source)) {
            this["operations"] = [];
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }
        if (!("conflicts" in $$source)) {
            this["conflicts"] = [];
        }
        if (!("drift" in $$source)) {
            this["drift"] = [];
        }
        if (!("previewHash" in $$source)) {
            this["previewHash"] = "";
        }
        if (!("canApply" in $$source)) {
            this["canApply"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preview instance from a string or object.
     */
    static createFrom($$source: any = {}): Preview {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType6;
        const $$createField3_0 = $$createType6;
        const $$createField4_0 = $$createType8;
        const $$createField5_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("request" in $$parsedSource) {
            $$parsedSource["request"] = $$createField0_0($$parsedSource["request"]);
        }
        if ("operations" in $$parsedSource) {
            $$parsedSource["operations"] = $$createField1_0($$parsedSource["operations"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField2_0($$parsedSource["warnings"]);
        }
        if ("conflicts" in $$parsedSource) {
            $$parsedSource["conflicts"] = $$createField3_0($$parsedSource["conflicts"]);
        }
        if ("drift" in $$parsedSource) {
            $$parsedSource["drift"] = $$createField4_0($$parsedSource["drift"]);
        }
        if ("desiredTarget" in $$parsedSource) {
            $$parsedSource["desiredTarget"] = $$createField5_0($$parsedSource["desiredTarget"]);
        }
        return new Preview($$parsedSource as Partial<Preview>);
    }
}

export class RecoveryState {
    "required": boolean;
    "journalId"?: string;
    "gameId"?: number;
    "targetPath"?: string;
    "action"?: Action;
    "startedAt"?: time$0.Time;
    "error"?: string;

    /** Creates a new RecoveryState instance. */
    constructor($$source: Partial<RecoveryState> = {}) {
        if (!("required" in $$source)) {
            this["required"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecoveryState instance from a string or object.
     */
    static createFrom($$source: any = {}): RecoveryState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecoveryState($$parsedSource as Partial<RecoveryState>);
    }
}

export enum RenderingAPI {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RenderingAPID3D9 = "d3d9",
    RenderingAPID3D10 = "d3d10",
    RenderingAPID3D11 = "d3d11",
    RenderingAPID3D12 = "d3d12",
};

export class Request {
    "action": Action;
    "gameId": number;
    "targetRelativePath": string;
    "executableRelativePath": string;
    "renderingApi": RenderingAPI;
    "proxyFilename": string;
    "architecture": Architecture;
    "buildVariant": BuildVariant;
    "backupAndContinue": boolean;

    /** Creates a new Request instance. */
    constructor($$source: Partial<Request> = {}) {
        if (!("action" in $$source)) {
            this["action"] = Action.$zero;
        }
        if (!("gameId" in $$source)) {
            this["gameId"] = 0;
        }
        if (!("targetRelativePath" in $$source)) {
            this["targetRelativePath"] = "";
        }
        if (!("executableRelativePath" in $$source)) {
            this["executableRelativePath"] = "";
        }
        if (!("renderingApi" in $$source)) {
            this["renderingApi"] = RenderingAPI.$zero;
        }
        if (!("proxyFilename" in $$source)) {
            this["proxyFilename"] = "";
        }
        if (!("architecture" in $$source)) {
            this["architecture"] = Architecture.$zero;
        }
        if (!("buildVariant" in $$source)) {
            this["buildVariant"] = BuildVariant.$zero;
        }
        if (!("backupAndContinue" in $$source)) {
            this["backupAndContinue"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Request instance from a string or object.
     */
    static createFrom($$source: any = {}): Request {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Request($$parsedSource as Partial<Request>);
    }
}

export class TargetState {
    "runtimeVersion": string;
    "provenance": InstallerProvenance;
    "managementOrigin": string;
    "manifest": Manifest;

    /** Creates a new TargetState instance. */
    constructor($$source: Partial<TargetState> = {}) {
        if (!("runtimeVersion" in $$source)) {
            this["runtimeVersion"] = "";
        }
        if (!("provenance" in $$source)) {
            this["provenance"] = (new InstallerProvenance());
        }
        if (!("managementOrigin" in $$source)) {
            this["managementOrigin"] = "";
        }
        if (!("manifest" in $$source)) {
            this["manifest"] = (new Manifest());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TargetState instance from a string or object.
     */
    static createFrom($$source: any = {}): TargetState {
        const $$createField1_0 = $$createType0;
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("provenance" in $$parsedSource) {
            $$parsedSource["provenance"] = $$createField1_0($$parsedSource["provenance"]);
        }
        if ("manifest" in $$parsedSource) {
            $$parsedSource["manifest"] = $$createField3_0($$parsedSource["manifest"]);
        }
        return new TargetState($$parsedSource as Partial<TargetState>);
    }
}

// Private type creation functions
const $$createType0 = InstallerProvenance.createFrom;
const $$createType1 = ManagedFile.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = Request.createFrom;
const $$createType4 = filetxn$0.Operation.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = Drift.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = TargetState.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = Manifest.createFrom;
