// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PersistedFileState {
    "GameID": number;
    "GameRelativePath": string;
    "ProfileID": number;
    "BaselineExists": boolean;
    "BaselineSHA256": string | null;
    "BaselineSizeBytes": number | null;
    "BaselineBackupPath": string | null;
    "AppliedExists": boolean;
    "AppliedSHA256": string | null;
    "AppliedSizeBytes": number | null;
    "WinningSourceKind": string | null;
    "WinningSourceID": string | null;
    "WinningModID": number | null;
    "WinningLoadOrder": number | null;
    "OutputKind": string;
    "UserDecision": string | null;
    "LastAppliedAt": string;

    /** Creates a new PersistedFileState instance. */
    constructor($$source: Partial<PersistedFileState> = {}) {
        if (!("GameID" in $$source)) {
            this["GameID"] = 0;
        }
        if (!("GameRelativePath" in $$source)) {
            this["GameRelativePath"] = "";
        }
        if (!("ProfileID" in $$source)) {
            this["ProfileID"] = 0;
        }
        if (!("BaselineExists" in $$source)) {
            this["BaselineExists"] = false;
        }
        if (!("BaselineSHA256" in $$source)) {
            this["BaselineSHA256"] = null;
        }
        if (!("BaselineSizeBytes" in $$source)) {
            this["BaselineSizeBytes"] = null;
        }
        if (!("BaselineBackupPath" in $$source)) {
            this["BaselineBackupPath"] = null;
        }
        if (!("AppliedExists" in $$source)) {
            this["AppliedExists"] = false;
        }
        if (!("AppliedSHA256" in $$source)) {
            this["AppliedSHA256"] = null;
        }
        if (!("AppliedSizeBytes" in $$source)) {
            this["AppliedSizeBytes"] = null;
        }
        if (!("WinningSourceKind" in $$source)) {
            this["WinningSourceKind"] = null;
        }
        if (!("WinningSourceID" in $$source)) {
            this["WinningSourceID"] = null;
        }
        if (!("WinningModID" in $$source)) {
            this["WinningModID"] = null;
        }
        if (!("WinningLoadOrder" in $$source)) {
            this["WinningLoadOrder"] = null;
        }
        if (!("OutputKind" in $$source)) {
            this["OutputKind"] = "";
        }
        if (!("UserDecision" in $$source)) {
            this["UserDecision"] = null;
        }
        if (!("LastAppliedAt" in $$source)) {
            this["LastAppliedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PersistedFileState instance from a string or object.
     */
    static createFrom($$source: any = {}): PersistedFileState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PersistedFileState($$parsedSource as Partial<PersistedFileState>);
    }
}
